// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface ActiveModelConfig_t : ISchemaClass {

  
  public ModelConfigHandle_t Handle { get; }
  
  public ref CUtlSymbolLarge Name { get; }
  
  public ref CUtlVector<CHandle<CBaseModelEntity>> AssociatedEntities { get; }
  
  public ref CUtlVector<CUtlSymbolLarge> AssociatedEntityNames { get; }

  public void HandleUpdated();
  public void NameUpdated();
  public void AssociatedEntitiesUpdated();
  public void AssociatedEntityNamesUpdated();
}