// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface AnimStateID : ISchemaClass, IConvertibleNativeHandle<AnimStateID> {

  static AnimStateID IConvertibleNativeHandle<AnimStateID>.From(nint handle) => new AnimStateIDImpl(handle);

  
  public ref uint Id { get; }


}