// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_INIT_RandomAlphaWindowThreshold : CParticleFunctionInitializer {

  
  public ref float Min { get; }
  
  public ref float Max { get; }
  
  public ref float Exponent { get; }


}