// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_INIT_ModelCull : CParticleFunctionInitializer {

  
  public ref int ControlPointNumber { get; }
  
  public ref bool BoundBox { get; }
  
  public ref bool CullOutside { get; }
  
  public ref bool UseBones { get; }
  
  public ISchemaFixedString HitboxSetName { get; }
}