// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_INIT_RandomModelSequence : CParticleFunctionInitializer, IConvertibleNativeHandle<C_INIT_RandomModelSequence> {

  static C_INIT_RandomModelSequence IConvertibleNativeHandle<C_INIT_RandomModelSequence>.From(nint handle) => new C_INIT_RandomModelSequenceImpl(handle);

  
  public ISchemaFixedString ActivityName { get; }
  
  public ISchemaFixedString SequenceName { get; }
  
  public ref CStrongHandle<InfoForResourceTypeCModel> Model { get; }


}