// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_INIT_MoveBetweenPoints : CParticleFunctionInitializer {

  
  public CPerParticleFloatInput SpeedMin { get; }
  
  public CPerParticleFloatInput SpeedMax { get; }
  
  public CPerParticleFloatInput EndSpread { get; }
  
  public CPerParticleFloatInput StartOffset { get; }
  
  public CPerParticleFloatInput EndOffset { get; }
  
  public ref int EndControlPointNumber { get; }
  
  public ref bool TrailBias { get; }


}