// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_INIT_CreateInEpitrochoid : CParticleFunctionInitializer {

  
  public ref int Component1 { get; }
  
  public ref int Component2 { get; }
  
  public CParticleTransformInput TransformInput { get; }
  
  public CPerParticleFloatInput ParticleDensity { get; }
  
  public CPerParticleFloatInput Offset { get; }
  
  public CPerParticleFloatInput Radius1 { get; }
  
  public CPerParticleFloatInput Radius2 { get; }
  
  public ref bool UseCount { get; }
  
  public ref bool UseLocalCoords { get; }
  
  public ref bool OffsetExistingPos { get; }


}