// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_INIT_SequenceLifeTime : CParticleFunctionInitializer, IConvertibleNativeHandle<C_INIT_SequenceLifeTime> {

  static C_INIT_SequenceLifeTime IConvertibleNativeHandle<C_INIT_SequenceLifeTime>.From(nint handle) => new C_INIT_SequenceLifeTimeImpl(handle);

  
  public ref float Framerate { get; }


}