// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_INIT_InitVec : CParticleFunctionInitializer {

  
  public CPerParticleVecInput InputValue { get; }
  
  public ParticleAttributeIndex_t OutputField { get; }
  
  public ref ParticleSetMethod_t SetMethod { get; }
  
  public ref bool NormalizedOutput { get; }
  
  public ref bool WritePreviousPosition { get; }
}