// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_INIT_SequenceFromCP : CParticleFunctionInitializer, IConvertibleNativeHandle<C_INIT_SequenceFromCP> {

  static C_INIT_SequenceFromCP IConvertibleNativeHandle<C_INIT_SequenceFromCP>.From(nint handle) => new C_INIT_SequenceFromCPImpl(handle);

  
  public ref bool KillUnused { get; }
  
  public ref bool RadiusScale { get; }
  
  public ref int CP { get; }
  
  public ref Vector Offset { get; }


}