// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_INIT_RandomVector : CParticleFunctionInitializer {

  
  public ref Vector Min { get; }
  
  public ref Vector Max { get; }
  
  public ParticleAttributeIndex_t FieldOutput { get; }
  
  public CRandomNumberGeneratorParameters RandomnessParameters { get; }


}