// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_INIT_CreateOnModel : CParticleFunctionInitializer {

  
  public CParticleModelInput ModelInput { get; }
  
  public CParticleTransformInput TransformInput { get; }
  
  public ref int ForceInModel { get; }
  
  public ref bool ScaleToVolume { get; }
  
  public ref bool EvenDistribution { get; }
  
  public CParticleCollectionFloatInput DesiredHitbox { get; }
  
  public ref int HitboxValueFromControlPointIndex { get; }
  
  public CParticleCollectionVecInput HitBoxScale { get; }
  
  public ref float BoneVelocity { get; }
  
  public ref float MaxBoneVelocity { get; }
  
  public CParticleCollectionVecInput DirectionBias { get; }
  
  public ISchemaFixedString HitboxSetName { get; }
  
  public ref bool LocalCoords { get; }
  
  public ref bool UseBones { get; }
  
  public ref bool UseMesh { get; }
  
  public CParticleCollectionFloatInput ShellSize { get; }


}