// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_INIT_LifespanFromVelocity : CParticleFunctionInitializer {

  
  public ref Vector ComponentScale { get; }
  
  public ref float TraceOffset { get; }
  
  public ref float MaxTraceLength { get; }
  
  public ref float TraceTolerance { get; }
  
  public ref int MaxPlanes { get; }
  
  public ISchemaFixedString CollisionGroupName { get; }
  
  public ref ParticleTraceSet_t TraceSet { get; }
  
  public ref bool IncludeWater { get; }


}