// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_INIT_InitialVelocityNoise : CParticleFunctionInitializer {

  
  public ref Vector AbsVal { get; }
  
  public ref Vector AbsValInv { get; }
  
  public CPerParticleVecInput OffsetLoc { get; }
  
  public CPerParticleFloatInput Offset { get; }
  
  public CPerParticleVecInput OutputMin { get; }
  
  public CPerParticleVecInput OutputMax { get; }
  
  public CPerParticleFloatInput NoiseScale { get; }
  
  public CPerParticleFloatInput NoiseScaleLoc { get; }
  
  public CParticleTransformInput TransformInput { get; }
  
  public ref bool IgnoreDt { get; }


}