// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_INIT_ChaoticAttractor : CParticleFunctionInitializer {

  
  public ref float AParm { get; }
  
  public ref float BParm { get; }
  
  public ref float CParm { get; }
  
  public ref float DParm { get; }
  
  public ref float Scale { get; }
  
  public ref float SpeedMin { get; }
  
  public ref float SpeedMax { get; }
  
  public ref int BaseCP { get; }
  
  public ref bool UniformSpeed { get; }
}