// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_INIT_SequenceFromCP : CParticleFunctionInitializer {

  
  public ref bool KillUnused { get; }
  
  public ref bool RadiusScale { get; }
  
  public ref int CP { get; }
  
  public ref Vector Offset { get; }


}