// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_INIT_InitFromCPSnapshot : CParticleFunctionInitializer {

  
  public ref int ControlPointNumber { get; }
  
  public ref CUtlString StrSnapshotSubset { get; }
  
  public ParticleAttributeIndex_t AttributeToRead { get; }
  
  public ParticleAttributeIndex_t AttributeToWrite { get; }
  
  public ref int LocalSpaceCP { get; }
  
  public ref bool Random { get; }
  
  public ref bool Reverse { get; }
  
  public CParticleCollectionFloatInput SnapShotIncrement { get; }
  
  public CPerParticleFloatInput ManualSnapshotIndex { get; }
  
  public ref int RandomSeed { get; }
  
  public ref bool LocalSpaceAngles { get; }
}