// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_VectorNoise : CParticleFunctionOperator {

  
  public ParticleAttributeIndex_t FieldOutput { get; }
  
  public ref Vector OutputMin { get; }
  
  public ref Vector OutputMax { get; }
  
  public ref float Fl4NoiseScale { get; }
  
  public ref bool Additive { get; }
  
  public ref bool Offset { get; }
  
  public ref float NoiseAnimationTimeScale { get; }


}