// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_LockPoints : CParticleFunctionOperator {

  
  public ref int MinCol { get; }
  
  public ref int MaxCol { get; }
  
  public ref int MinRow { get; }
  
  public ref int MaxRow { get; }
  
  public ref int ControlPoint { get; }
  
  public ref float BlendValue { get; }


}