// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_DriveCPFromGlobalSoundFloat : CParticleFunctionPreEmission, IConvertibleNativeHandle<C_OP_DriveCPFromGlobalSoundFloat> {

  static C_OP_DriveCPFromGlobalSoundFloat IConvertibleNativeHandle<C_OP_DriveCPFromGlobalSoundFloat>.From(nint handle) => new C_OP_DriveCPFromGlobalSoundFloatImpl(handle);

  
  public ref int OutputControlPoint { get; }
  
  public ref int OutputField { get; }
  
  public ref float InputMin { get; }
  
  public ref float InputMax { get; }
  
  public ref float OutputMin { get; }
  
  public ref float OutputMax { get; }
  
  public ref CUtlString StackName { get; }
  
  public ref CUtlString OperatorName { get; }
  
  public ref CUtlString FieldName { get; }


}