// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_RenderMaterialProxy : CParticleFunctionRenderer {

  
  public ref int MaterialControlPoint { get; }
  
  public ref MaterialProxyType_t ProxyType { get; }
  
  // CUtlVector< MaterialVariable_t >
  public ref CUtlVector MaterialVars { get; }
  
  public ref CStrongHandle<InfoForResourceTypeIMaterial2> OverrideMaterial { get; }
  
  public CParticleCollectionFloatInput MaterialOverrideEnabled { get; }
  
  public CParticleCollectionVecInput ColorScale { get; }
  
  public CPerParticleFloatInput Alpha { get; }
  
  public ref ParticleColorBlendType_t ColorBlendType { get; }


}