// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_InterpolateRadius : CParticleFunctionOperator {

  
  public ref float StartTime { get; }
  
  public ref float EndTime { get; }
  
  public ref float StartScale { get; }
  
  public ref float EndScale { get; }
  
  public ref bool EaseInAndOut { get; }
  
  public ref float Bias { get; }


}