// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_ConstrainDistance : CParticleFunctionConstraint {

  
  public CParticleCollectionFloatInput MinDistance { get; }
  
  public CParticleCollectionFloatInput MaxDistance { get; }
  
  public ref int ControlPointNumber { get; }
  
  public ref Vector CenterOffset { get; }
  
  public ref bool GlobalCenter { get; }


}