// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_RemapBoundingVolumetoCP : CParticleFunctionPreEmission, IConvertibleNativeHandle<C_OP_RemapBoundingVolumetoCP> {

  static C_OP_RemapBoundingVolumetoCP IConvertibleNativeHandle<C_OP_RemapBoundingVolumetoCP>.From(nint handle) => new C_OP_RemapBoundingVolumetoCPImpl(handle);

  
  public ref int OutControlPointNumber { get; }
  
  public ref float InputMin { get; }
  
  public ref float InputMax { get; }
  
  public ref float OutputMin { get; }
  
  public ref float OutputMax { get; }


}