// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_RemapTransformOrientationToRotations : CParticleFunctionOperator {

  
  public CParticleTransformInput TransformInput { get; }
  
  public ref Vector Rotation { get; }
  
  public ref bool UseQuat { get; }
  
  public ref bool WriteNormal { get; }


}