// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_LockToSavedSequentialPathV2 : CParticleFunctionOperator {

  
  public ref float FadeStart { get; }
  
  public ref float FadeEnd { get; }
  
  public ref bool CPPairs { get; }
  
  public CPathParameters PathParams { get; }
}