// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_EnableChildrenFromParentParticleCount : CParticleFunctionPreEmission, IConvertibleNativeHandle<C_OP_EnableChildrenFromParentParticleCount> {

  static C_OP_EnableChildrenFromParentParticleCount IConvertibleNativeHandle<C_OP_EnableChildrenFromParentParticleCount>.From(nint handle) => new C_OP_EnableChildrenFromParentParticleCountImpl(handle);

  
  public ref int ChildGroupID { get; }
  
  public ref int FirstChild { get; }
  
  public CParticleCollectionFloatInput NumChildrenToEnable { get; }
  
  public ref bool DisableChildren { get; }
  
  public ref bool PlayEndcapOnStop { get; }
  
  public ref bool DestroyImmediately { get; }


}