// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_PinParticleToCP : CParticleFunctionOperator {

  
  public ref int ControlPointNumber { get; }
  
  public CParticleCollectionVecInput Offset { get; }
  
  public ref bool OffsetLocal { get; }
  
  public ref ParticleSelection_t ParticleSelection { get; }
  
  public CParticleCollectionFloatInput ParticleNumber { get; }
  
  public ref ParticlePinDistance_t PinBreakType { get; }
  
  public CParticleCollectionFloatInput BreakDistance { get; }
  
  public CParticleCollectionFloatInput BreakSpeed { get; }
  
  public CParticleCollectionFloatInput Age { get; }
  
  public ref int BreakControlPointNumber { get; }
  
  public ref int BreakControlPointNumber2 { get; }
  
  public CParticleCollectionFloatInput BreakValue { get; }
  
  public CPerParticleFloatInput Interpolation { get; }
  
  public ref bool RetainInitialVelocity { get; }


}