// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_RenderStatusEffectCitadel : CParticleFunctionRenderer {

  
  public ref CStrongHandle<InfoForResourceTypeCTextureBase> TextureColorWarp { get; }
  
  public ref CStrongHandle<InfoForResourceTypeCTextureBase> TextureNormal { get; }
  
  public ref CStrongHandle<InfoForResourceTypeCTextureBase> TextureMetalness { get; }
  
  public ref CStrongHandle<InfoForResourceTypeCTextureBase> TextureRoughness { get; }
  
  public ref CStrongHandle<InfoForResourceTypeCTextureBase> TextureSelfIllum { get; }
  
  public ref CStrongHandle<InfoForResourceTypeCTextureBase> TextureDetail { get; }


}