// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_DecayMaintainCount : CParticleFunctionOperator {

  
  public ref int ParticlesToMaintain { get; }
  
  public ref float DecayDelay { get; }
  
  public ref int SnapshotControlPoint { get; }
  
  public ref bool LifespanDecay { get; }
  
  public CParticleCollectionFloatInput Scale { get; }
  
  public ref bool KillNewest { get; }
}