// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_RenderFlattenGrass : CParticleFunctionRenderer {

  
  public ref float FlattenStrength { get; }
  
  public ParticleAttributeIndex_t StrengthFieldOverride { get; }
  
  public ref float RadiusScale { get; }


}