// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_RenderOmni2Light : CParticleFunctionRenderer {

  
  public ref ParticleOmni2LightTypeChoiceList_t LightType { get; }
  
  public CParticleCollectionVecInput ColorBlend { get; }
  
  public ref ParticleColorBlendType_t ColorBlendType { get; }
  
  public ref ParticleLightUnitChoiceList_t BrightnessUnit { get; }
  
  public CPerParticleFloatInput BrightnessLumens { get; }
  
  public CPerParticleFloatInput BrightnessCandelas { get; }
  
  public ref bool CastShadows { get; }
  
  public ref bool Fog { get; }
  
  public CPerParticleFloatInput FogScale { get; }
  
  public CPerParticleFloatInput LuminaireRadius { get; }
  
  public CPerParticleFloatInput Skirt { get; }
  
  public CPerParticleFloatInput Range { get; }
  
  public CPerParticleFloatInput InnerConeAngle { get; }
  
  public CPerParticleFloatInput OuterConeAngle { get; }
  
  public ref CStrongHandle<InfoForResourceTypeCTextureBase> LightCookie { get; }
  
  public ref bool SphericalCookie { get; }


}