// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_LockToSavedSequentialPathV2 : CParticleFunctionOperator, IConvertibleNativeHandle<C_OP_LockToSavedSequentialPathV2> {

  static C_OP_LockToSavedSequentialPathV2 IConvertibleNativeHandle<C_OP_LockToSavedSequentialPathV2>.From(nint handle) => new C_OP_LockToSavedSequentialPathV2Impl(handle);

  
  public ref float FadeStart { get; }
  
  public ref float FadeEnd { get; }
  
  public ref bool CPPairs { get; }
  
  public CPathParameters PathParams { get; }


}