// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_RenderBlobs : CParticleFunctionRenderer, IConvertibleNativeHandle<C_OP_RenderBlobs> {

  static C_OP_RenderBlobs IConvertibleNativeHandle<C_OP_RenderBlobs>.From(nint handle) => new C_OP_RenderBlobsImpl(handle);

  
  public CParticleCollectionRendererFloatInput CubeWidth { get; }
  
  public CParticleCollectionRendererFloatInput CutoffRadius { get; }
  
  public CParticleCollectionRendererFloatInput RenderRadius { get; }
  
  public ref uint VertexCountKb { get; }
  
  public ref uint IndexCountKb { get; }
  
  public ref int ScaleCP { get; }
  
  // CUtlVector< MaterialVariable_t >
  public ref CUtlVector MaterialVars { get; }
  
  public ref CStrongHandle<InfoForResourceTypeIMaterial2> Material { get; }


}