// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_LerpToInitialPosition : CParticleFunctionOperator, IConvertibleNativeHandle<C_OP_LerpToInitialPosition> {

  static C_OP_LerpToInitialPosition IConvertibleNativeHandle<C_OP_LerpToInitialPosition>.From(nint handle) => new C_OP_LerpToInitialPositionImpl(handle);

  
  public ref int ControlPointNumber { get; }
  
  public CPerParticleFloatInput Interpolation { get; }
  
  public ParticleAttributeIndex_t CacheField { get; }
  
  public CParticleCollectionFloatInput Scale { get; }
  
  public CParticleCollectionVecInput Scale1 { get; }


}