// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_ScreenSpaceDistanceToEdge : CParticleFunctionOperator, IConvertibleNativeHandle<C_OP_ScreenSpaceDistanceToEdge> {

  static C_OP_ScreenSpaceDistanceToEdge IConvertibleNativeHandle<C_OP_ScreenSpaceDistanceToEdge>.From(nint handle) => new C_OP_ScreenSpaceDistanceToEdgeImpl(handle);

  
  public ParticleAttributeIndex_t FieldOutput { get; }
  
  public CPerParticleFloatInput MaxDistFromEdge { get; }
  
  public CParticleRemapFloatInput OutputRemap { get; }
  
  public ref ParticleSetMethod_t SetMethod { get; }


}