// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_RenderText : CParticleFunctionRenderer {

  
  public ref Color OutlineColor { get; }
  
  public ref CUtlString DefaultText { get; }


}