// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_MovementPlaceOnGround : CParticleFunctionOperator {

  
  public CPerParticleFloatInput Offset { get; }
  
  public ref float MaxTraceLength { get; }
  
  public ref float Tolerance { get; }
  
  public ref float TraceOffset { get; }
  
  public ref float LerpRate { get; }
  
  public ISchemaFixedString CollisionGroupName { get; }
  
  public ref ParticleTraceSet_t TraceSet { get; }
  
  public ref int RefCP1 { get; }
  
  public ref int RefCP2 { get; }
  
  public ref int LerpCP { get; }
  
  public ref ParticleTraceMissBehavior_t TraceMissBehavior { get; }
  
  public ref bool IncludeShotHull { get; }
  
  public ref bool IncludeWater { get; }
  
  public ref bool SetNormal { get; }
  
  public ref bool ScaleOffset { get; }
  
  public ref int PreserveOffsetCP { get; }
  
  public ref int IgnoreCP { get; }


}