// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_AttractToControlPoint : CParticleFunctionForce, IConvertibleNativeHandle<C_OP_AttractToControlPoint> {

  static C_OP_AttractToControlPoint IConvertibleNativeHandle<C_OP_AttractToControlPoint>.From(nint handle) => new C_OP_AttractToControlPointImpl(handle);

  
  public ref Vector ComponentScale { get; }
  
  public CPerParticleFloatInput ForceAmount { get; }
  
  public ref float FalloffPower { get; }
  
  public CParticleTransformInput TransformInput { get; }
  
  public CPerParticleFloatInput ForceAmountMin { get; }
  
  public ref bool ApplyMinForce { get; }


}