// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_RemapDotProductToCP : CParticleFunctionPreEmission {

  
  public ref int InputCP1 { get; }
  
  public ref int InputCP2 { get; }
  
  public ref int OutputCP { get; }
  
  public ref int OutVectorField { get; }
  
  public CParticleCollectionFloatInput InputMin { get; }
  
  public CParticleCollectionFloatInput InputMax { get; }
  
  public CParticleCollectionFloatInput OutputMin { get; }
  
  public CParticleCollectionFloatInput OutputMax { get; }


}