// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_RemapSpeedtoCP : CParticleFunctionPreEmission {

  
  public ref int InControlPointNumber { get; }
  
  public ref int OutControlPointNumber { get; }
  
  public ref int Field { get; }
  
  public ref float InputMin { get; }
  
  public ref float InputMax { get; }
  
  public ref float OutputMin { get; }
  
  public ref float OutputMax { get; }
  
  public ref bool UseDeltaV { get; }


}