// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_DistanceBetweenVecs : CParticleFunctionOperator {

  
  public ParticleAttributeIndex_t FieldOutput { get; }
  
  public CPerParticleVecInput Point1 { get; }
  
  public CPerParticleVecInput Point2 { get; }
  
  public CPerParticleFloatInput InputMin { get; }
  
  public CPerParticleFloatInput InputMax { get; }
  
  public CPerParticleFloatInput OutputMin { get; }
  
  public CPerParticleFloatInput OutputMax { get; }
  
  public ref ParticleSetMethod_t SetMethod { get; }
  
  public ref bool DeltaTime { get; }


}