// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_QuantizeCPComponent : CParticleFunctionPreEmission {

  
  public CParticleCollectionFloatInput InputValue { get; }
  
  public ref int CPOutput { get; }
  
  public ref int OutVectorField { get; }
  
  public CParticleCollectionFloatInput QuantizeValue { get; }


}