// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_TimeVaryingForce : CParticleFunctionForce, IConvertibleNativeHandle<C_OP_TimeVaryingForce> {

  static C_OP_TimeVaryingForce IConvertibleNativeHandle<C_OP_TimeVaryingForce>.From(nint handle) => new C_OP_TimeVaryingForceImpl(handle);

  
  public ref float StartLerpTime { get; }
  
  public ref Vector StartingForce { get; }
  
  public ref float EndLerpTime { get; }
  
  public ref Vector EndingForce { get; }


}