// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_DampenToCP : CParticleFunctionOperator, IConvertibleNativeHandle<C_OP_DampenToCP> {

  static C_OP_DampenToCP IConvertibleNativeHandle<C_OP_DampenToCP>.From(nint handle) => new C_OP_DampenToCPImpl(handle);

  
  public ref int ControlPointNumber { get; }
  
  public ref float Range { get; }
  
  public ref float Scale { get; }


}