// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_RenderLights : C_OP_RenderPoints {

  
  public ref float AnimationRate { get; }
  
  public ref AnimationType_t AnimationType { get; }
  
  public ref bool AnimateInFPS { get; }
  
  public ref float MinSize { get; }
  
  public ref float MaxSize { get; }
  
  public ref float StartFadeSize { get; }
  
  public ref float EndFadeSize { get; }


}