// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_ScreenSpaceDistanceToEdge : CParticleFunctionOperator {

  
  public ParticleAttributeIndex_t FieldOutput { get; }
  
  public CPerParticleFloatInput MaxDistFromEdge { get; }
  
  public CParticleRemapFloatInput OutputRemap { get; }
  
  public ref ParticleSetMethod_t SetMethod { get; }


}