// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_SetControlPointToVectorExpression : CParticleFunctionPreEmission {

  
  public ref VectorExpressionType_t Expression { get; }
  
  public ref int OutputCP { get; }
  
  public CParticleCollectionVecInput Input1 { get; }
  
  public CParticleCollectionVecInput Input2 { get; }
  
  public CPerParticleFloatInput Lerp { get; }
  
  public ref bool NormalizedOutput { get; }
}