// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_SpringToVectorConstraint : CParticleFunctionConstraint {

  
  public CPerParticleFloatInput RestLength { get; }
  
  public CPerParticleFloatInput MinDistance { get; }
  
  public CPerParticleFloatInput MaxDistance { get; }
  
  public CPerParticleFloatInput RestingLength { get; }
  
  public CPerParticleVecInput AnchorVector { get; }


}