// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_ExternalWindForce : CParticleFunctionForce {

  
  public CPerParticleVecInput SamplePosition { get; }
  
  public CPerParticleVecInput Scale { get; }
  
  public ref bool SampleWind { get; }
  
  public ref bool SampleWater { get; }
  
  public ref bool DampenNearWaterPlane { get; }
  
  public ref bool SampleGravity { get; }
  
  public CPerParticleVecInput GravityForce { get; }
  
  public ref bool UseBasicMovementGravity { get; }
  
  public CPerParticleFloatInput LocalGravityScale { get; }
  
  public CPerParticleFloatInput LocalBuoyancyScale { get; }
  
  public CPerParticleVecInput BuoyancyForce { get; }


}