// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_SDFLighting : CParticleFunctionOperator {

  
  public ref Vector LightingDir { get; }
  
  public ref Vector Tint_0 { get; }
  
  public ref Vector Tint_1 { get; }


}