// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_LerpEndCapScalar : CParticleFunctionOperator {

  
  public ParticleAttributeIndex_t FieldOutput { get; }
  
  public ref float Output { get; }
  
  public ref float LerpTime { get; }
}