// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_InheritFromPeerSystem : CParticleFunctionOperator {

  
  public ParticleAttributeIndex_t FieldOutput { get; }
  
  public ParticleAttributeIndex_t FieldInput { get; }
  
  public ref int Increment { get; }
  
  public ref int GroupID { get; }
}