// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CActionComponentUpdater : CAnimComponentUpdater, IConvertibleNativeHandle<CActionComponentUpdater> {

  static CActionComponentUpdater IConvertibleNativeHandle<CActionComponentUpdater>.From(nint handle) => new CActionComponentUpdaterImpl(handle);

  
  // CUtlVector< CSmartPtr< CAnimActionUpdater > >
  public ref CUtlVector Actions { get; }


}