// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAI_ExpresserWithFollowup : CAI_Expresser, IConvertibleNativeHandle<CAI_ExpresserWithFollowup> {

  static CAI_ExpresserWithFollowup IConvertibleNativeHandle<CAI_ExpresserWithFollowup>.From(nint handle) => new CAI_ExpresserWithFollowupImpl(handle);




}