// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimInputDamping : ISchemaClass {

  
  public ref DampingSpeedFunction SpeedFunction { get; }
  
  public ref float SpeedScale { get; }
  
  public ref float FallingSpeedScale { get; }


}