// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimUpdateNodeBase : ISchemaClass {

  
  public CAnimNodePath NodePath { get; }
  
  public ref AnimNodeNetworkMode NetworkMode { get; }
  
  public ref CUtlString Name { get; }


}