// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimationGroup : ISchemaClass {

  
  public ref uint Flags { get; }
  
  public ref CBufferString Name { get; }
  
  public ref CUtlVector<CStrongHandle<InfoForResourceTypeCAnimData>> LocalHAnimArray_Handle { get; }
  
  public ref CUtlVector<CStrongHandle<InfoForResourceTypeCAnimationGroup>> IncludedGroupArray_Handle { get; }
  
  public ref CStrongHandle<InfoForResourceTypeCSequenceGroupData> DirectHSeqGroup_Handle { get; }
  
  public CAnimKeyData DecodeKey { get; }
  
  public ref CUtlVector<CBufferString> Scripts { get; }
  
// CUtlVector< CStrongHandleVoid >
  public ref CUtlVector AdditionalExtRefs { get; }


}