// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimData : ISchemaClass<CAnimData> {

  static CAnimData ISchemaClass<CAnimData>.From(nint handle) => new CAnimDataImpl(handle);

  
  public ref CBufferString Name { get; }
  
  // CUtlVector< CAnimDesc >
  public ref CUtlVector AnimArray { get; }
  
  // CUtlVector< CAnimDecoder >
  public ref CUtlVector DecoderArray { get; }
  
  public ref int MaxUniqueFrameIndex { get; }
  
  // CUtlVector< CAnimFrameSegment >
  public ref CUtlVector SegmentArray { get; }


}