// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimInputDamping : ISchemaClass, IConvertibleNativeHandle<CAnimInputDamping> {

  static CAnimInputDamping IConvertibleNativeHandle<CAnimInputDamping>.From(nint handle) => new CAnimInputDampingImpl(handle);

  
  public ref DampingSpeedFunction SpeedFunction { get; }
  
  public ref float SpeedScale { get; }
  
  public ref float FallingSpeedScale { get; }


}