// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimDesc_Flag : ISchemaClass {

  
  public ref bool Looping { get; }
  
  public ref bool AllZeros { get; }
  
  public ref bool Hidden { get; }
  
  public ref bool Delta { get; }
  
  public ref bool LegacyWorldspace { get; }
  
  public ref bool ModelDoc { get; }
  
  public ref bool ImplicitSeqIgnoreDelta { get; }
  
  public ref bool AnimGraphAdditive { get; }


}