// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimGraphControllerBase : ISchemaClass {

  
  // CUtlVectorFixedGrowable< CGlobalSymbol, 8 >
  public SchemaUntypedField ParamsToResetInPostGraphUpdate { get; }


}