// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimGraphModelBinding : ISchemaClass<CAnimGraphModelBinding> {

  static CAnimGraphModelBinding ISchemaClass<CAnimGraphModelBinding>.From(nint handle) => new CAnimGraphModelBindingImpl(handle);

  
  public ref CUtlString ModelName { get; }
  
  // CSmartPtr< CAnimUpdateSharedData >
  public SchemaUntypedField SharedData { get; }


}