// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimScriptManager : ISchemaClass, IConvertibleNativeHandle<CAnimScriptManager> {

  static CAnimScriptManager IConvertibleNativeHandle<CAnimScriptManager>.From(nint handle) => new CAnimScriptManagerImpl(handle);

  
  // CUtlVector< ScriptInfo_t >
  public ref CUtlVector ScriptInfo { get; }


}