// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimUserDifference : ISchemaClass {

  
  public ref CBufferString Name { get; }
  
  public ref int Type { get; }


}