// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimEncodedFrames : ISchemaClass {

  
  public ref CBufferString FileName { get; }
  
  public ref int Frames { get; }
  
  public ref int FramesPerBlock { get; }
  
  // CUtlVector< CAnimFrameBlockAnim >
  public ref CUtlVector FrameblockArray { get; }
  
  public CAnimEncodeDifference UsageDifferences { get; }


}