// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimFrameSegment : ISchemaClass {

  
  public ref int UniqueFrameIndex { get; }
  
  public ref uint LocalElementMasks { get; }
  
  public ref int LocalChannel { get; }
  
  public ref CUtlBinaryBlock Container { get; }
}