// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimActivity : ISchemaClass, IConvertibleNativeHandle<CAnimActivity> {

  static CAnimActivity IConvertibleNativeHandle<CAnimActivity>.From(nint handle) => new CAnimActivityImpl(handle);

  
  public ref CBufferString Name { get; }
  
  public ref int Activity { get; }
  
  public ref int Flags { get; }
  
  public ref int Weight { get; }


}