// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAudioAnimTag : CAnimTagBase {

  
  public ref CUtlString ClipName { get; }
  
  public ref CUtlString AttachmentName { get; }
  
  public ref float Volume { get; }
  
  public ref bool StopWhenTagEnds { get; }
  
  public ref bool StopWhenGraphEnds { get; }
  
  public ref bool PlayOnServer { get; }
  
  public ref bool PlayOnClient { get; }


}