// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CBaseConstraint : CBoneConstraintBase {

  
  public ref CUtlString Name { get; }
  
  public ref Vector UpVector { get; }
  
  public SchemaUntypedField Slaves { get; }
  
// CUtlVector< CConstraintTarget >
  public ref CUtlVector Targets { get; }


}