// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CBasePlayerControllerAPI : ISchemaClass, IConvertibleNativeHandle<CBasePlayerControllerAPI> {

  static CBasePlayerControllerAPI IConvertibleNativeHandle<CBasePlayerControllerAPI>.From(nint handle) => new CBasePlayerControllerAPIImpl(handle);




}