// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CBoneConstraintPoseSpaceMorph__Input_t : ISchemaClass, IConvertibleNativeHandle<CBoneConstraintPoseSpaceMorph__Input_t> {

  static CBoneConstraintPoseSpaceMorph__Input_t IConvertibleNativeHandle<CBoneConstraintPoseSpaceMorph__Input_t>.From(nint handle) => new CBoneConstraintPoseSpaceMorph__Input_tImpl(handle);

  
  public ref Vector InputValue { get; }
  
  public ref CUtlVector<float> OutputWeightList { get; }


}