// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CBoneConstraintPoseSpaceBone : CBaseConstraint, IConvertibleNativeHandle<CBoneConstraintPoseSpaceBone> {

  static CBoneConstraintPoseSpaceBone IConvertibleNativeHandle<CBoneConstraintPoseSpaceBone>.From(nint handle) => new CBoneConstraintPoseSpaceBoneImpl(handle);

  
  // CUtlVector< CBoneConstraintPoseSpaceBone::Input_t >
  public ref CUtlVector InputList { get; }


}