// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CBtActionAim : CBtNode {

  
  public ref CUtlString SensorInputKey { get; }
  
  public ref CUtlString AimReadyKey { get; }
  
  public ref float ZoomCooldownTimestamp { get; }
  
  public ref bool DoneAiming { get; }
  
  public ref float LerpStartTime { get; }
  
  public ref float NextLookTargetLerpTime { get; }
  
  public ref float PenaltyReductionRatio { get; }
  
  public ref QAngle NextLookTarget { get; }
  
  public CountdownTimer AimTimer { get; }
  
  public CountdownTimer SniperHoldTimer { get; }
  
  public CountdownTimer FocusIntervalTimer { get; }
  
  public ref bool Acquired { get; }
}