// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CCachedPose : ISchemaClass {

  
  public ref CUtlVector<CTransform> Transforms { get; }
  
  public ref CUtlVector<float> MorphWeights { get; }
  
  public HSequence Sequence { get; }
  
  public ref float Cycle { get; }
}