// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CChicken_GraphController : CBaseAnimGraphAnimGraphController {

  
  public SchemaUntypedField ParamActivity { get; }
  
  public SchemaUntypedField ParamEndActivityImmediately { get; }
  
  public SchemaUntypedField ActivityFinished { get; }
  
  public SchemaUntypedField ParamTurnAngle { get; }
}