// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CClothSettingsAnimTag : CAnimTagBase {

  
  public ref float Stiffness { get; }
  
  public ref float EaseIn { get; }
  
  public ref float EaseOut { get; }
  
  public ref CUtlString VertexSet { get; }


}