// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CColorCorrection : CBaseEntity {

  
  public ref float FadeInDuration { get; }
  
  public ref float FadeOutDuration { get; }
  
  public ref float StartFadeInWeight { get; }
  
  public ref float StartFadeOutWeight { get; }
  
  public GameTime_t TimeStartFadeIn { get; }
  
  public GameTime_t TimeStartFadeOut { get; }
  
  public ref float MaxWeight { get; }
  
  public ref bool StartDisabled { get; }
  
  public ref bool Enabled { get; }
  
  public ref bool Master { get; }
  
  public ref bool ClientSide { get; }
  
  public ref bool Exclusive { get; }
  
  public ref float MinFalloff { get; }
  
  public ref float MaxFalloff { get; }
  
  public ref float CurWeight { get; }
  
  public ISchemaFixedString NetlookupFilename { get; }
  
  public ref CUtlSymbolLarge LookupFilename { get; }

  public void FadeInDurationUpdated();
  public void FadeOutDurationUpdated();
  public void MaxWeightUpdated();
  public void EnabledUpdated();
  public void MasterUpdated();
  public void ClientSideUpdated();
  public void ExclusiveUpdated();
  public void MinFalloffUpdated();
  public void MaxFalloffUpdated();
  public void CurWeightUpdated();
  public void NetlookupFilenameUpdated();
}