// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CCredits : CPointEntity {

  
  public CEntityIOOutput OnCreditsDone { get; }
  
  public ref bool RolledOutroCredits { get; }
  
  public ref float LogoLength { get; }


}