// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CCSGameModeRules : ISchemaClass {

  
  public CNetworkVarChainer __m_pChainEntity { get; }


}