// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CCSPointScriptExtensions_CCSWeaponBaseVData : ISchemaClass<CCSPointScriptExtensions_CCSWeaponBaseVData> {

  static CCSPointScriptExtensions_CCSWeaponBaseVData ISchemaClass<CCSPointScriptExtensions_CCSWeaponBaseVData>.From(nint handle) => new CCSPointScriptExtensions_CCSWeaponBaseVDataImpl(handle);




}