// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CCSPlayer_ItemServices : CPlayer_ItemServices {

  
  public ref bool HasDefuser { get; }
  
  public ref bool HasHelmet { get; }

  public void HasDefuserUpdated();
  public void HasHelmetUpdated();
}