// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CDestructiblePartsSystemData_DamageLevel : ISchemaClass {

  
  public ref CUtlString Name { get; }
  
  public ref CGlobalSymbol BreakablePieceName { get; }
  
  public ref int BodyGroupValue { get; }
  
  public CSkillInt Health { get; }
  
  public ref EDestructiblePartDamagePassThroughType DamagePassthroughType { get; }
  
  public ref DestructiblePartDestructionDeathBehavior_t DestructionDeathBehavior { get; }
  
  public ref CGlobalSymbol CustomDeathHandshake { get; }
  
  public ref bool ShouldDestroyOnDeath { get; }
  
  public CRangeFloat DeathDestroyTime { get; }


}