// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CDestructiblePartsSystemData : ISchemaClass {

  
  // CUtlOrderedMap< HitGroup_t, CDestructiblePartsSystemData_HitGroupInfoAndDamageLevels >
  public SchemaUntypedField PartsDataByHitGroup { get; }
  
  public CRangeInt MinMaxNumberHitGroupsToDestroyWhenGibbing { get; }


}