// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CDirectPlaybackTagData : ISchemaClass, IConvertibleNativeHandle<CDirectPlaybackTagData> {

  static CDirectPlaybackTagData IConvertibleNativeHandle<CDirectPlaybackTagData>.From(nint handle) => new CDirectPlaybackTagDataImpl(handle);

  
  public ref CUtlString SequenceName { get; }
  
  // CUtlVector< TagSpan_t >
  public ref CUtlVector Tags { get; }


}