// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CEntityComponentHelper : ISchemaClass {

  
  public ref uint Flags { get; }
  
  public EntComponentInfo_t? Info { get; }
  
  public ref int Priority { get; }
  
  public CEntityComponentHelper? Next { get; }


}