// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CFilterMultiple : CBaseFilter, ISchemaClass<CFilterMultiple> {

  static CFilterMultiple ISchemaClass<CFilterMultiple>.From(nint handle) => new CFilterMultipleImpl(handle);

  
  public ref filter_t FilterType { get; }
  
  public string FilterName { get; set; }
  
  public ISchemaFixedArray<CHandle<CBaseEntity>> Filter { get; }


}