// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CFilterEnemy : CBaseFilter {

  
  public ref CUtlSymbolLarge EnemyName { get; }
  
  public ref float Radius { get; }
  
  public ref float OuterRadius { get; }
  
  public ref int MaxSquadmatesPerEnemy { get; }
  
  public ref CUtlSymbolLarge PlayerName { get; }


}