// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CFootstepLandedAnimTag : CAnimTagBase {

  
  public ref FootstepLandedFootSoundType_t FootstepType { get; }
  
  public ref CUtlString OverrideSoundName { get; }
  
  public ref CUtlString DebugAnimSourceString { get; }
  
  public ref CUtlString BoneName { get; }
}