// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CFootDefinition : ISchemaClass<CFootDefinition> {

  static CFootDefinition ISchemaClass<CFootDefinition>.From(nint handle) => new CFootDefinitionImpl(handle);

  
  public ref CUtlString Name { get; }
  
  public ref CUtlString AnkleBoneName { get; }
  
  public ref CUtlString ToeBoneName { get; }
  
  public ref Vector BallOffset { get; }
  
  public ref Vector HeelOffset { get; }
  
  public ref float FootLength { get; }
  
  public ref float BindPoseDirectionMS { get; }
  
  public ref float TraceHeight { get; }
  
  public ref float TraceRadius { get; }


}