// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CFuncShatterglass : CBaseModelEntity, IConvertibleNativeHandle<CFuncShatterglass> {

  static CFuncShatterglass IConvertibleNativeHandle<CFuncShatterglass>.From(nint handle) => new CFuncShatterglassImpl(handle);

  
  public ref matrix3x4_t MatPanelTransform { get; }
  
  public ref matrix3x4_t MatPanelTransformWsTemp { get; }
  
  public ref CUtlVector<uint> ShatterGlassShards { get; }
  
  public ref Vector2D PanelSize { get; }
  
  public GameTime_t LastShatterSoundEmitTime { get; }
  
  public GameTime_t LastCleanupTime { get; }
  
  public GameTime_t InitAtTime { get; }
  
  public ref float GlassThickness { get; }
  
  public ref float SpawnInvulnerability { get; }
  
  public ref bool BreakSilent { get; }
  
  public ref bool BreakShardless { get; }
  
  public ref bool Broken { get; }
  
  public ref bool GlassNavIgnore { get; }
  
  public ref bool GlassInFrame { get; }
  
  public ref bool StartBroken { get; }
  
  public ref byte InitialDamageType { get; }
  
  public ref CUtlSymbolLarge DamagePositioningEntityName01 { get; }
  
  public ref CUtlSymbolLarge DamagePositioningEntityName02 { get; }
  
  public ref CUtlSymbolLarge DamagePositioningEntityName03 { get; }
  
  public ref CUtlSymbolLarge DamagePositioningEntityName04 { get; }
  
  public ref CUtlVector<Vector> InitialDamagePositions { get; }
  
  public ref CUtlVector<Vector> ExtraDamagePositions { get; }
  
  public ref CUtlVector<Vector4D> InitialPanelVertices { get; }
  
  public CEntityIOOutput OnBroken { get; }
  
  public ref byte SurfaceType { get; }
  
  public ref CStrongHandle<InfoForResourceTypeIMaterial2> MaterialDamageBase { get; }


}