// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CFuncBrush : CBaseModelEntity {

  
  public ref BrushSolidities_e Solidity { get; }
  
  public ref int Disabled { get; }
  
  public ref bool SolidBsp { get; }
  
  public ref CUtlSymbolLarge ExcludedClass { get; }
  
  public ref bool InvertExclusion { get; }
  
  public ref bool ScriptedMovement { get; }


}