// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CFutureVelocityMetricEvaluator : CMotionMetricEvaluator, IConvertibleNativeHandle<CFutureVelocityMetricEvaluator> {

  static CFutureVelocityMetricEvaluator IConvertibleNativeHandle<CFutureVelocityMetricEvaluator>.From(nint handle) => new CFutureVelocityMetricEvaluatorImpl(handle);

  
  public ref float Distance { get; }
  
  public ref float StoppingDistance { get; }
  
  public ref float TargetSpeed { get; }
  
  public ref VelocityMetricMode Mode { get; }


}