// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CFutureVelocityMetricEvaluator : CMotionMetricEvaluator {

  
  public ref float Distance { get; }
  
  public ref float StoppingDistance { get; }
  
  public ref float TargetSpeed { get; }
  
  public ref VelocityMetricMode Mode { get; }


}