// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CFutureFacingMetricEvaluator : CMotionMetricEvaluator {

  
  public ref float Distance { get; }
  
  public ref float Time { get; }
}