// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CGamePlayerEquip : CRulePointEntity, IConvertibleNativeHandle<CGamePlayerEquip> {

  static CGamePlayerEquip IConvertibleNativeHandle<CGamePlayerEquip>.From(nint handle) => new CGamePlayerEquipImpl(handle);




}