// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CGradientFog : CBaseEntity {

  
  public ref CStrongHandle<InfoForResourceTypeCTextureBase> GradientFogTexture { get; }
  
  public ref float FogStartDistance { get; }
  
  public ref float FogEndDistance { get; }
  
  public ref bool HeightFogEnabled { get; }
  
  public ref float FogStartHeight { get; }
  
  public ref float FogEndHeight { get; }
  
  public ref float FarZ { get; }
  
  public ref float FogMaxOpacity { get; }
  
  public ref float FogFalloffExponent { get; }
  
  public ref float FogVerticalExponent { get; }
  
  public ref Color FogColor { get; }
  
  public ref float FogStrength { get; }
  
  public ref float FadeTime { get; }
  
  public ref bool StartDisabled { get; }
  
  public ref bool IsEnabled { get; }
  
  public ref bool GradientFogNeedsTextures { get; }

  public void GradientFogTextureUpdated();
  public void FogStartDistanceUpdated();
  public void FogEndDistanceUpdated();
  public void HeightFogEnabledUpdated();
  public void FogStartHeightUpdated();
  public void FogEndHeightUpdated();
  public void FarZUpdated();
  public void FogMaxOpacityUpdated();
  public void FogFalloffExponentUpdated();
  public void FogVerticalExponentUpdated();
  public void FogColorUpdated();
  public void FogStrengthUpdated();
  public void FadeTimeUpdated();
  public void StartDisabledUpdated();
  public void IsEnabledUpdated();
}