// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CHitBoxSet : ISchemaClass {

  
  public ref CUtlString Name { get; }
  
  public ref uint NameHash { get; }
  
  // CUtlVector< CHitBox >
  public ref CUtlVector HitBoxes { get; }
  
  public ref CUtlString SourceFilename { get; }


}