// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CHostageRescueZone : CHostageRescueZoneShim, IConvertibleNativeHandle<CHostageRescueZone> {

  static CHostageRescueZone IConvertibleNativeHandle<CHostageRescueZone>.From(nint handle) => new CHostageRescueZoneImpl(handle);




}