// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CInfoSpawnGroupLoadUnload : CLogicalEntity {

  
  public CEntityIOOutput OnSpawnGroupLoadStarted { get; }
  
  public CEntityIOOutput OnSpawnGroupLoadFinished { get; }
  
  public CEntityIOOutput OnSpawnGroupUnloadStarted { get; }
  
  public CEntityIOOutput OnSpawnGroupUnloadFinished { get; }
  
  public ref CUtlSymbolLarge SpawnGroupName { get; }
  
  public ref CUtlSymbolLarge SpawnGroupFilterName { get; }
  
  public ref CUtlSymbolLarge LandmarkName { get; }
  
  public ref CUtlString FixedSpawnGroupName { get; }
  
  public ref float TimeoutInterval { get; }
  
  public ref bool AutoActivate { get; }
  
  public ref bool UnloadingStarted { get; }
  
  public ref bool QueueActiveSpawnGroupChange { get; }
  
  public ref bool QueueFinishLoading { get; }


}