// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CInfoVisibilityBox : CBaseEntity {

  
  public ref int Mode { get; }
  
  public ref Vector BoxSize { get; }
  
  public ref bool Enabled { get; }

  public void ModeUpdated();
  public void BoxSizeUpdated();
  public void EnabledUpdated();
}