// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CInstructorEventEntity : CPointEntity, ISchemaClass<CInstructorEventEntity> {

  static CInstructorEventEntity ISchemaClass<CInstructorEventEntity>.From(nint handle) => new CInstructorEventEntityImpl(handle);

  
  public ref CUtlSymbolLarge Name { get; }
  
  public ref CUtlSymbolLarge HintTargetEntity { get; }
  
  public ref CHandle<CBasePlayerPawn> TargetPlayer { get; }


}