// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CIntAnimParameter : CConcreteAnimParameter {

  
  public ref int DefaultValue { get; }
  
  public ref int MinValue { get; }
  
  public ref int MaxValue { get; }


}