// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CLogicGameEvent : CLogicalEntity, IConvertibleNativeHandle<CLogicGameEvent> {

  static CLogicGameEvent IConvertibleNativeHandle<CLogicGameEvent>.From(nint handle) => new CLogicGameEventImpl(handle);

  
  public ref CUtlSymbolLarge EventName { get; }


}