// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CLogicPlayerProxy : CLogicalEntity, IConvertibleNativeHandle<CLogicPlayerProxy> {

  static CLogicPlayerProxy IConvertibleNativeHandle<CLogicPlayerProxy>.From(nint handle) => new CLogicPlayerProxyImpl(handle);

  
  public ref CHandle<CBaseEntity> Player { get; }
  
  public CEntityIOOutput PlayerHasAmmo { get; }
  
  public CEntityIOOutput PlayerHasNoAmmo { get; }
  
  public CEntityIOOutput PlayerDied { get; }
  
  // CEntityOutputTemplate< int32 >
  public SchemaUntypedField RequestedPlayerHealth { get; }


}