// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CLogicGameEventListener : CLogicalEntity, ISchemaClass<CLogicGameEventListener> {

  static CLogicGameEventListener ISchemaClass<CLogicGameEventListener>.From(nint handle) => new CLogicGameEventListenerImpl(handle);

  
  public CEntityIOOutput OnEventFired { get; }
  
  public ref CUtlSymbolLarge GameEventName { get; }
  
  public ref CUtlSymbolLarge GameEventItem { get; }
  
  public ref bool Enabled { get; }
  
  public ref bool StartDisabled { get; }

  public void EnabledUpdated();
}