// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CMarkupVolumeTagged_NavGame : CMarkupVolumeWithRef {

  
  public ref NavScopeFlags_t Scopes { get; }
  
  public ref bool FloodFillAttribute { get; }
  
  public ref bool SplitNavSpace { get; }
}