// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CMaterialDrawDescriptor__RigidMeshPart_t : ISchemaClass {

  
  public ref ushort RigidBLASIndex { get; }
  
  public ref short BoneIndex { get; }
  
  public ref uint StartIndexOffset { get; }
  
  public ref uint PrimitiveCount { get; }


}