// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CMolotovProjectile : CBaseCSGrenadeProjectile {

  
  public ref bool IsIncGrenade { get; }
  
  public ref bool Detonated { get; }
  
  public IntervalTimer StillTimer { get; }
  
  public ref bool HasBouncedOffPlayer { get; }

  public void IsIncGrenadeUpdated();
}