// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CMotionSearchNode : ISchemaClass {

  
  public ref CUtlVector<PointerTo<CMotionSearchNode>> Children { get; }
  
  public CVectorQuantizer Quantizer { get; }
  
  public ref CUtlVector<CUtlVector> SampleCodes { get; }
  
  public ref CUtlVector<CUtlVector<int>> SampleIndices { get; }
  
  public ref CUtlVector<int> SelectableSamples { get; }


}