// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CMovementComponentUpdater : CAnimComponentUpdater {

  
  // CUtlVector< CSmartPtr< CAnimMotorUpdaterBase > >
  public ref CUtlVector Motors { get; }
  
  public CAnimInputDamping FacingDamping { get; }
  
  public ref int DefaultMotorIndex { get; }
  
  public ref float DefaultRunSpeed { get; }
  
  public ref bool MoveVarsDisabled { get; }
  
  public ref bool NetworkPath { get; }
  
  public ref bool NetworkFacing { get; }
  
  // CAnimParamHandle
  public SchemaUntypedField ParamHandles { get; }


}