// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CMultiLightProxy : CLogicalEntity, IConvertibleNativeHandle<CMultiLightProxy> {

  static CMultiLightProxy IConvertibleNativeHandle<CMultiLightProxy>.From(nint handle) => new CMultiLightProxyImpl(handle);

  
  public ref CUtlSymbolLarge LightNameFilter { get; }
  
  public ref CUtlSymbolLarge LightClassFilter { get; }
  
  public ref float LightRadiusFilter { get; }
  
  public ref float BrightnessDelta { get; }
  
  public ref bool PerformScreenFade { get; }
  
  public ref float TargetBrightnessMultiplier { get; }
  
  public ref float CurrentBrightnessMultiplier { get; }
  
  public ref CUtlVector<CHandle<CLightEntity>> Lights { get; }


}