// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmAnimationPoseNode__CDefinition : CNmPoseNode__CDefinition {

  
  public ref short PoseTimeValueNodeIdx { get; }
  
  public ref short DataSlotIdx { get; }
  
  // Range_t
  public SchemaUntypedField InputTimeRemapRange { get; }
  
  public ref float UserSpecifiedTime { get; }
  
  public ref bool UseFramesAsInput { get; }


}