// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmBoneWeightList : ISchemaClass {

  
  // CResourceName
  public SchemaUntypedField SkeletonName { get; }
  
  public ref CUtlVector<CGlobalSymbol> BoneIDs { get; }
  
  public ref CUtlVector<float> Weights { get; }


}