// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmCachedFloatNode__CDefinition : CNmFloatValueNode__CDefinition, IConvertibleNativeHandle<CNmCachedFloatNode__CDefinition> {

  static CNmCachedFloatNode__CDefinition IConvertibleNativeHandle<CNmCachedFloatNode__CDefinition>.From(nint handle) => new CNmCachedFloatNode__CDefinitionImpl(handle);

  
  public ref short InputValueNodeIdx { get; }
  
  public ref NmCachedValueMode_t Mode { get; }


}