// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmConstTargetNode__CDefinition : CNmTargetValueNode__CDefinition {

  
  public CNmTarget Value { get; }


}