// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmDurationScaleNode__CDefinition : CNmSpeedScaleBaseNode__CDefinition {


}