// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmFootstepEventPercentageThroughNode__CDefinition : CNmFloatValueNode__CDefinition {

  
  public ref short SourceStateNodeIdx { get; }
  
  public ref NmFootPhaseCondition_t PhaseCondition { get; }
  
  public CNmBitFlags EventConditionRules { get; }


}