// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmFloatClampNode__CDefinition : CNmFloatValueNode__CDefinition, IConvertibleNativeHandle<CNmFloatClampNode__CDefinition> {

  static CNmFloatClampNode__CDefinition IConvertibleNativeHandle<CNmFloatClampNode__CDefinition>.From(nint handle) => new CNmFloatClampNode__CDefinitionImpl(handle);

  
  public ref short InputValueNodeIdx { get; }
  
  // Range_t
  public SchemaUntypedField ClampRange { get; }


}