// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmGraphNode__CDefinition : ISchemaClass {

  
  public ref short NodeIdx { get; }


}