// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmIDComparisonNode__CDefinition : CNmBoolValueNode__CDefinition, IConvertibleNativeHandle<CNmIDComparisonNode__CDefinition> {

  static CNmIDComparisonNode__CDefinition IConvertibleNativeHandle<CNmIDComparisonNode__CDefinition>.From(nint handle) => new CNmIDComparisonNode__CDefinitionImpl(handle);

  
  public ref short InputValueNodeIdx { get; }
  
  public ref CNmIDComparisonNode__Comparison_t Comparison { get; }
  
  // CUtlLeanVectorFixedGrowable< CGlobalSymbol, 4 >
  public SchemaUntypedField ComparisionIDs { get; }


}