// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmIKRig : ISchemaClass {

  
  public ref CStrongHandle<InfoForResourceTypeCNmSkeleton> Skeleton { get; }
  
  // CUtlVector< CNmIKBody >
  public ref CUtlVector Bodies { get; }
  
  // CUtlVector< CNmIKJoint >
  public ref CUtlVector Joints { get; }


}