// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmLayerBlendNode__LayerDefinition_t : ISchemaClass {

  
  public ref short InputNodeIdx { get; }
  
  public ref short WeightValueNodeIdx { get; }
  
  public ref short BoneMaskValueNodeIdx { get; }
  
  public ref short RootMotionWeightValueNodeIdx { get; }
  
  public ref bool IsSynchronized { get; }
  
  public ref bool IgnoreEvents { get; }
  
  public ref bool IsStateMachineLayer { get; }
  
  public ref NmPoseBlendMode_t BlendMode { get; }
}