// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmLayerBlendNode__CDefinition : CNmPoseNode__CDefinition {

  
  public ref short BaseNodeIdx { get; }
  
  public ref bool OnlySampleBaseRootMotion { get; }
  
  // CUtlLeanVectorFixedGrowable< CNmLayerBlendNode::LayerDefinition_t, 3 >
  public SchemaUntypedField LayerDefinition { get; }


}