// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmMaterialAttributeEvent : CNmEvent, IConvertibleNativeHandle<CNmMaterialAttributeEvent> {

  static CNmMaterialAttributeEvent IConvertibleNativeHandle<CNmMaterialAttributeEvent>.From(nint handle) => new CNmMaterialAttributeEventImpl(handle);

  
  public ref CUtlString AttributeName { get; }
  
  public ref CUtlStringToken AttributeNameToken { get; }
  
  // CPiecewiseCurve
  public SchemaUntypedField X { get; }
  
  // CPiecewiseCurve
  public SchemaUntypedField Y { get; }
  
  // CPiecewiseCurve
  public SchemaUntypedField Z { get; }
  
  // CPiecewiseCurve
  public SchemaUntypedField W { get; }


}