// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmParameterizedBlendNode__BlendRange_t : ISchemaClass {

  
  public ref short InputIdx0 { get; }
  
  public ref short InputIdx1 { get; }
  
  public SchemaUntypedField ParameterValueRange { get; }


}