// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmReferencedGraphNode__CDefinition : CNmPoseNode__CDefinition {

  
  public ref short ReferencedGraphIdx { get; }
  
  public ref short FallbackNodeIdx { get; }
}