// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmStateCompletedConditionNode__CDefinition : CNmBoolValueNode__CDefinition {

  
  public ref short SourceStateNodeIdx { get; }
  
  public ref short TransitionDurationOverrideNodeIdx { get; }
  
  public ref float TransitionDurationSeconds { get; }


}