// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmSoundEvent : CNmEvent, ISchemaClass<CNmSoundEvent> {

  static CNmSoundEvent ISchemaClass<CNmSoundEvent>.From(nint handle) => new CNmSoundEventImpl(handle);

  
  public ref CNmEventRelevance_t Relevance { get; }
  
  public ref CNmSoundEvent__Type_t Type { get; }
  
  public ref CUtlString Name { get; }
  
  public ref CNmSoundEvent__Position_t Position { get; }
  
  public ref CUtlString AttachmentName { get; }
  
  public ref CUtlString Tags { get; }
  
  public ref bool IsServerOnly { get; }
  
  public ref bool ContinuePlayingSoundAtDurationEnd { get; }
  
  public ref float DurationInterruptionThreshold { get; }


}