// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmSoundEvent : CNmEvent {

  
  public ref CNmEventRelevance_t Relevance { get; }
  
  public ref CNmSoundEvent__Type_t Type { get; }
  
  public ref CUtlString Name { get; }
  
  public ref CNmSoundEvent__Position_t Position { get; }
  
  public ref CUtlString AttachmentName { get; }
  
  public ref CUtlString Tags { get; }
  
  public ref bool IsServerOnly { get; }
  
  public ref bool ContinuePlayingSoundAtDurationEnd { get; }
  
  public ref float DurationInterruptionThreshold { get; }


}