// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmStateNode__TimedEvent_t : ISchemaClass {

  
  public ref CGlobalSymbol ID { get; }
  
  public ref float TimeValueSeconds { get; }
  
  public ref CNmStateNode__TimedEvent_t__Comparison_t ComparisionOperator { get; }


}