// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmSyncTrack : ISchemaClass {

  
  public SchemaUntypedField SyncEvents { get; }
  
  public ref int StartEventOffset { get; }


}