// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmStateMachineNode__TransitionDefinition_t : ISchemaClass {

  
  public ref short TargetStateIdx { get; }
  
  public ref short ConditionNodeIdx { get; }
  
  public ref short TransitionNodeIdx { get; }
  
  public ref bool CanBeForced { get; }
}