// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmVirtualParameterTargetNode__CDefinition : CNmTargetValueNode__CDefinition, IConvertibleNativeHandle<CNmVirtualParameterTargetNode__CDefinition> {

  static CNmVirtualParameterTargetNode__CDefinition IConvertibleNativeHandle<CNmVirtualParameterTargetNode__CDefinition>.From(nint handle) => new CNmVirtualParameterTargetNode__CDefinitionImpl(handle);

  
  public ref short ChildNodeIdx { get; }


}