// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmZeroPoseNode__CDefinition : CNmPoseNode__CDefinition, IConvertibleNativeHandle<CNmZeroPoseNode__CDefinition> {

  static CNmZeroPoseNode__CDefinition IConvertibleNativeHandle<CNmZeroPoseNode__CDefinition>.From(nint handle) => new CNmZeroPoseNode__CDefinitionImpl(handle);




}