// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface ConstraintSoundInfo : ISchemaClass<ConstraintSoundInfo> {

  static ConstraintSoundInfo ISchemaClass<ConstraintSoundInfo>.From(nint handle) => new ConstraintSoundInfoImpl(handle);

  
  public VelocitySampler Sampler { get; }
  
  public SimpleConstraintSoundProfile SoundProfile { get; }
  
  public ref Vector ForwardAxis { get; }
  
  public ref CUtlSymbolLarge TravelSoundFwd { get; }
  
  public ref CUtlSymbolLarge TravelSoundBack { get; }
  
  public ISchemaFixedArray<CUtlSymbolLarge> ReversalSounds { get; }
  
  public ref bool PlayTravelSound { get; }
  
  public ref bool PlayReversalSound { get; }


}