// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CountdownTimer : ISchemaClass {

  
  public ref float Duration { get; }
  
  public GameTime_t Timestamp { get; }
  
  public ref float Timescale { get; }
  
  public ref uint WorldGroupId { get; }
}