// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CParticleCollectionBindingInstance : CBasePulseGraphInstance, IConvertibleNativeHandle<CParticleCollectionBindingInstance> {

  static CParticleCollectionBindingInstance IConvertibleNativeHandle<CParticleCollectionBindingInstance>.From(nint handle) => new CParticleCollectionBindingInstanceImpl(handle);




}