// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CParticleModelInput : CParticleInput {

  
  public ref ParticleModelType_t Type { get; }
  
  public SchemaUntypedField NamedValue { get; }
  
  public ref int ControlPoint { get; }
}