// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPathKeyFrame : CLogicalEntity {

  
  public ref Vector Origin { get; }
  
  public ref QAngle Angles { get; }
  
  public ref Quaternion Angle { get; }
  
  public ref CUtlSymbolLarge NextKey { get; }
  
  public ref float NextTime { get; }
  
  public CPathKeyFrame NextKey1 { get; }
  
  public CPathKeyFrame PrevKey { get; }
  
  public ref float MoveSpeed { get; }


}