// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPathMetricEvaluator : CMotionMetricEvaluator, IConvertibleNativeHandle<CPathMetricEvaluator> {

  static CPathMetricEvaluator IConvertibleNativeHandle<CPathMetricEvaluator>.From(nint handle) => new CPathMetricEvaluatorImpl(handle);

  
  public ref CUtlVector<float> PathTimeSamples { get; }
  
  public ref float Distance { get; }
  
  public ref bool ExtrapolateMovement { get; }
  
  public ref float MinExtrapolationSpeed { get; }


}