// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPathCorner : CPointEntity, IConvertibleNativeHandle<CPathCorner> {

  static CPathCorner IConvertibleNativeHandle<CPathCorner>.From(nint handle) => new CPathCornerImpl(handle);

  
  public ref float Wait { get; }
  
  public ref float Radius { get; }
  
  public CEntityIOOutput OnPass { get; }


}