// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPhysConstraint : CLogicalEntity, ISchemaClass<CPhysConstraint> {

  static CPhysConstraint ISchemaClass<CPhysConstraint>.From(nint handle) => new CPhysConstraintImpl(handle);

  
  public ref CUtlSymbolLarge NameAttach1 { get; }
  
  public ref CUtlSymbolLarge NameAttach2 { get; }
  
  public ref CHandle<CBaseEntity> Attach1 { get; }
  
  public ref CHandle<CBaseEntity> Attach2 { get; }
  
  public ref CUtlSymbolLarge NameAttachment1 { get; }
  
  public ref CUtlSymbolLarge NameAttachment2 { get; }
  
  public ref CUtlSymbolLarge BreakSound { get; }
  
  public ref float ForceLimit { get; }
  
  public ref float TorqueLimit { get; }
  
  public ref float MinTeleportDistance { get; }
  
  public ref bool SnapObjectPositions { get; }
  
  public CEntityIOOutput OnBreak { get; }


}