// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPhysTorque : CPhysForce, IConvertibleNativeHandle<CPhysTorque> {

  static CPhysTorque IConvertibleNativeHandle<CPhysTorque>.From(nint handle) => new CPhysTorqueImpl(handle);

  
  public ref Vector Axis { get; }


}