// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPhysLength : CPhysConstraint {

  
  public ISchemaFixedArray<Vector> Offset { get; }
  
  public ref Vector Attach { get; }
  
  public ref float AddLength { get; }
  
  public ref float MinLength { get; }
  
  public ref float TotalLength { get; }
  
  public ref bool EnableCollision { get; }


}