// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPlayerVisibility : CBaseEntity {

  
  public ref float VisibilityStrength { get; }
  
  public ref float FogDistanceMultiplier { get; }
  
  public ref float FogMaxDensityMultiplier { get; }
  
  public ref float FadeTime { get; }
  
  public ref bool StartDisabled { get; }
  
  public ref bool IsEnabled { get; }

  public void VisibilityStrengthUpdated();
  public void FogDistanceMultiplierUpdated();
  public void FogMaxDensityMultiplierUpdated();
  public void FadeTimeUpdated();
  public void StartDisabledUpdated();
  public void IsEnabledUpdated();
}