// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPointPrefab : CServerOnlyPointEntity, IConvertibleNativeHandle<CPointPrefab> {

  static CPointPrefab IConvertibleNativeHandle<CPointPrefab>.From(nint handle) => new CPointPrefabImpl(handle);

  
  public ref CUtlSymbolLarge TargetMapName { get; }
  
  public ref CUtlSymbolLarge ForceWorldGroupID { get; }
  
  public ref CUtlSymbolLarge AssociatedRelayTargetName { get; }
  
  public ref bool FixupNames { get; }
  
  public ref bool LoadDynamic { get; }
  
  public ref CHandle<CPointPrefab> AssociatedRelayEntity { get; }


}