// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPointOrient : CBaseEntity {

  
  public ref CUtlSymbolLarge SpawnTargetName { get; }
  
  public ref CHandle<CBaseEntity> Target { get; }
  
  public ref bool Active { get; }
  
  public ref PointOrientGoalDirectionType_t GoalDirection { get; }
  
  public ref PointOrientConstraint_t Constraint { get; }
  
  public ref float MaxTurnRate { get; }
  
  public GameTime_t LastGameTime { get; }


}