// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPointEntityFinder : CBaseEntity {

  
  public ref CHandle<CBaseEntity> Entity { get; }
  
  public ref CUtlSymbolLarge FilterName { get; }
  
  public ref CHandle<CBaseFilter> Filter { get; }
  
  public ref CUtlSymbolLarge RefName { get; }
  
  public ref CHandle<CBaseEntity> Reference { get; }
  
  public ref EntFinderMethod_t FindMethod { get; }
  
  public CEntityIOOutput OnFoundEntity { get; }


}