// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPoseHandle : ISchemaClass {

  
  public ref ushort Index { get; }
  
  public ref PoseType_t Type { get; }


}