// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPropDoorRotatingBreakable : CPropDoorRotating {

  
  public ref bool Breakable { get; }
  
  public ref bool IsAbleToCloseAreaPortals { get; }
  
  public ref int CurrentDamageState { get; }
  
  public ref CUtlVector<CUtlSymbolLarge> DamageStates { get; }


}