// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPulse_Variable : ISchemaClass {

  
  // PulseSymbol_t
  public SchemaUntypedField Name { get; }
  
  public ref CUtlString Description { get; }
  
  // CPulseValueFullType
  public SchemaUntypedField Type { get; }
  
  // KeyValues3
  public SchemaUntypedField DefaultValue { get; }
  
  public ref PulseVariableKeysSource_t KeysSource { get; }
  
  public ref bool IsPublicBlackboardVariable { get; }
  
  public ref bool IsObservable { get; }
  
  public PulseDocNodeID_t EditorNodeID { get; }


}