// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPulseRuntimeMethodArg : ISchemaClass {

  
  // CKV3MemberNameWithStorage
  public SchemaUntypedField Name { get; }
  
  public ref CUtlString Description { get; }
  
  // CPulseValueFullType
  public SchemaUntypedField Type { get; }


}