// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPulse_CallInfo : ISchemaClass, IConvertibleNativeHandle<CPulse_CallInfo> {

  static CPulse_CallInfo IConvertibleNativeHandle<CPulse_CallInfo>.From(nint handle) => new CPulse_CallInfoImpl(handle);

  
  // PulseSymbol_t
  public SchemaUntypedField PortName { get; }
  
  public PulseDocNodeID_t EditorNodeID { get; }
  
  public PulseRegisterMap_t RegisterMap { get; }
  
  public PulseDocNodeID_t CallMethodID { get; }
  
  public PulseRuntimeChunkIndex_t SrcChunk { get; }
  
  public ref int SrcInstruction { get; }


}