// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPulseCell_Outflow_ListenForEntityOutput : CPulseCell_BaseYieldingInflow {

  
  public SignatureOutflow_Resume OnFired { get; }
  
  public CPulse_ResumePoint OnCanceled { get; }
  
  public ref CGlobalSymbol StrEntityOutput { get; }
  
  public ref CUtlString StrEntityOutputParam { get; }
  
  public ref bool ListenUntilCanceled { get; }
}