// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPulse_CallInfo : ISchemaClass {

  
  public SchemaUntypedField PortName { get; }
  
  public PulseDocNodeID_t EditorNodeID { get; }
  
  public PulseRegisterMap_t RegisterMap { get; }
  
  public PulseDocNodeID_t CallMethodID { get; }
  
  public PulseRuntimeChunkIndex_t SrcChunk { get; }
  
  public ref int SrcInstruction { get; }
}