// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPulseCell_Outflow_TestRandomYesNo : CPulseCell_BaseFlow, IConvertibleNativeHandle<CPulseCell_Outflow_TestRandomYesNo> {

  static CPulseCell_Outflow_TestRandomYesNo IConvertibleNativeHandle<CPulseCell_Outflow_TestRandomYesNo>.From(nint handle) => new CPulseCell_Outflow_TestRandomYesNoImpl(handle);

  
  public CPulse_OutflowConnection Yes { get; }
  
  public CPulse_OutflowConnection No { get; }


}