// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPulseCell_Outflow_CycleShuffled__InstanceState_t : ISchemaClass {

  
  // CUtlVectorFixedGrowable< uint8, 8 >
  public SchemaUntypedField Shuffle { get; }
  
  public ref int NextShuffle { get; }


}