// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPulseCell_Inflow_Method : CPulseCell_Inflow_BaseEntrypoint {

  
  public SchemaUntypedField MethodName { get; }
  
  public ref CUtlString Description { get; }
  
  public ref bool IsPublic { get; }
  
  public SchemaUntypedField ReturnType { get; }
  
  public SchemaUntypedField Args { get; }


}