// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPulseCell_Step_FollowEntity : CPulseCell_BaseFlow {

  
  public ref CUtlString ParamBoneOrAttachName { get; }
  
  public ref CUtlString ParamBoneOrAttachNameChild { get; }


}