// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPulseCell_Outflow_IntSwitch : CPulseCell_BaseFlow, IConvertibleNativeHandle<CPulseCell_Outflow_IntSwitch> {

  static CPulseCell_Outflow_IntSwitch IConvertibleNativeHandle<CPulseCell_Outflow_IntSwitch>.From(nint handle) => new CPulseCell_Outflow_IntSwitchImpl(handle);

  
  public CPulse_OutflowConnection DefaultCaseOutflow { get; }
  
  // CUtlVector< CPulse_OutflowConnection >
  public ref CUtlVector CaseOutflows { get; }


}