// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CRagdollPropAttached : CRagdollProp {

  
  public ref uint BoneIndexAttached { get; }
  
  public ref uint RagdollAttachedObjectIndex { get; }
  
  public ref Vector AttachmentPointBoneSpace { get; }
  
  public ref Vector AttachmentPointRagdollSpace { get; }
  
  public ref bool ShouldDetach { get; }
  
  public ref bool ShouldDeleteAttachedActivationRecord { get; }
}