// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CRandSimTimer : CSimpleSimTimer {

  
  public ref float MinInterval { get; }
  
  public ref float MaxInterval { get; }


}