// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CRelativeLocation : ISchemaClass {

  
  public ref RelativeLocationType_t Type { get; }
  
  public ref Vector RelativeOffset { get; }
  
  public ref Vector WorldSpacePos { get; }
  
  public ref CHandle<CBaseEntity> Entity { get; }


}