// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CSceneListManager : CLogicalEntity {

  
  public ref CUtlVector<CHandle<CSceneListManager>> ListManagers { get; }
  
  public ISchemaFixedArray<CUtlSymbolLarge> Scenes { get; }
  
  public ISchemaFixedArray<CHandle<CBaseEntity>> Scenes1 { get; }


}