// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CSequenceTagSpans : ISchemaClass {

  
  public ref CGlobalSymbol SequenceName { get; }
  
  // CUtlVector< TagSpan_t >
  public ref CUtlVector Tags { get; }


}