// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CSeqScaleSet : ISchemaClass, IConvertibleNativeHandle<CSeqScaleSet> {

  static CSeqScaleSet IConvertibleNativeHandle<CSeqScaleSet>.From(nint handle) => new CSeqScaleSetImpl(handle);

  
  public ref CBufferString Name { get; }
  
  public ref bool RootOffset { get; }
  
  public ref Vector RootOffset1 { get; }
  
  public ref CUtlVector<short> LocalBoneArray { get; }
  
  public ref CUtlVector<float> BoneScaleArray { get; }


}