// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CSetParameterActionUpdater : CAnimActionUpdater {

  
  public CAnimParamHandle Param { get; }
  
  // CAnimVariant
  public SchemaUntypedField Value { get; }


}