// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CShatterGlassShardPhysics : CPhysicsProp, IConvertibleNativeHandle<CShatterGlassShardPhysics> {

  static CShatterGlassShardPhysics IConvertibleNativeHandle<CShatterGlassShardPhysics>.From(nint handle) => new CShatterGlassShardPhysicsImpl(handle);

  
  public ref bool Debris { get; }
  
  public ref uint ParentShard { get; }
  
  public shard_model_desc_t ShardDesc { get; }

  public void ShardDescUpdated();
}