// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CSkeletonAnimationController : ISkeletonAnimationController, IConvertibleNativeHandle<CSkeletonAnimationController> {

  static CSkeletonAnimationController IConvertibleNativeHandle<CSkeletonAnimationController>.From(nint handle) => new CSkeletonAnimationControllerImpl(handle);

  
  public CSkeletonInstance? SkeletonInstance { get; }


}