// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CSkyCamera : CBaseEntity {

  
  public sky3dparams_t SkyboxData { get; }
  
  public ref CUtlStringToken SkyboxSlotToken { get; }
  
  public ref bool UseAngles { get; }
  
  public CSkyCamera Next { get; }

  public void SkyboxDataUpdated();
  public void SkyboxSlotTokenUpdated();
}