// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CSmokeGrenadeProjectile : CBaseCSGrenadeProjectile {

  
  public ref int SmokeEffectTickBegin { get; }
  
  public ref bool DidSmokeEffect { get; }
  
  public ref int RandomSeed { get; }
  
  public ref Vector SmokeColor { get; }
  
  public ref Vector SmokeDetonationPos { get; }
  
  public ref CUtlVector<byte> VoxelFrameData { get; }
  
  public ref int VoxelFrameDataSize { get; }
  
  public ref int VoxelUpdate { get; }
  
  public GameTime_t LastBounce { get; }
  
  public GameTime_t FllastSimulationTime { get; }
  
  public ref bool ExplodeFromInferno { get; }
  
  public ref bool DidGroundScorch { get; }

  public void SmokeEffectTickBeginUpdated();
  public void DidSmokeEffectUpdated();
  public void RandomSeedUpdated();
  public void SmokeColorUpdated();
  public void SmokeDetonationPosUpdated();
  public void VoxelFrameDataUpdated();
  public void VoxelFrameDataSizeUpdated();
  public void VoxelUpdateUpdated();
}