// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CSolveIKChainUpdateNode : CUnaryUpdateNode {

  
  // CUtlVector< CSolveIKTargetHandle_t >
  public ref CUtlVector TargetHandles { get; }
  
  public SolveIKChainPoseOpFixedSettings_t OpFixedData { get; }


}