// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CSosSoundEventGroupListSchema : ISchemaClass<CSosSoundEventGroupListSchema> {

  static CSosSoundEventGroupListSchema ISchemaClass<CSosSoundEventGroupListSchema>.From(nint handle) => new CSosSoundEventGroupListSchemaImpl(handle);

  
  // CUtlVector< CSosSoundEventGroupSchema >
  public ref CUtlVector GroupList { get; }


}