// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CSosGroupActionTimeLimitSchema : CSosGroupActionSchema {

  
  public ref float MaxDuration { get; }


}