// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CSosGroupBranchPattern : ISchemaClass {

  
  public ref bool MatchEventName { get; }
  
  public ref bool MatchEventSubString { get; }
  
  public ref bool MatchEntIndex { get; }
  
  public ref bool MatchOpvar { get; }
  
  public ref bool MatchString { get; }


}