// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CSoundPatch : ISchemaClass {

  
  public CSoundEnvelope Pitch { get; }
  
  public CSoundEnvelope Volume { get; }
  
  public ref float ShutdownTime { get; }
  
  public ref float LastTime { get; }
  
  public ref CUtlSymbolLarge SoundScriptName { get; }
  
  public ref CHandle<CBaseEntity> Ent { get; }
  
  public ref uint SoundEntityIndex { get; }
  
  public ref Vector SoundOrigin { get; }
  
  public ref int IsPlaying { get; }
  
  public CCopyRecipientFilter Filter { get; }
  
  public ref float CloseCaptionDuration { get; }
  
  public ref bool UpdatedSoundOrigin { get; }
  
  public ref CUtlSymbolLarge ClassName { get; }


}