// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CSoundAreaEntityOrientedBox : CSoundAreaEntityBase, IConvertibleNativeHandle<CSoundAreaEntityOrientedBox> {

  static CSoundAreaEntityOrientedBox IConvertibleNativeHandle<CSoundAreaEntityOrientedBox>.From(nint handle) => new CSoundAreaEntityOrientedBoxImpl(handle);

  
  public ref Vector Min { get; }
  
  public ref Vector Max { get; }

  public void MinUpdated();
  public void MaxUpdated();
}