// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CSoundEventEntity : CBaseEntity {

  
  public ref bool StartOnSpawn { get; }
  
  public ref bool ToLocalPlayer { get; }
  
  public ref bool StopOnNew { get; }
  
  public ref bool SaveRestore { get; }
  
  public ref bool SavedIsPlaying { get; }
  
  public ref float SavedElapsedTime { get; }
  
  public ref CUtlSymbolLarge SourceEntityName { get; }
  
  public ref CUtlSymbolLarge AttachmentName { get; }
  
  // CEntityOutputTemplate< uint64 >
  public SchemaUntypedField OnGUIDChanged { get; }
  
  public CEntityIOOutput OnSoundFinished { get; }
  
  public ref float ClientCullRadius { get; }
  
  public ref CUtlSymbolLarge SoundName { get; }
  
  public ref CHandle<CEntityInstance> Source { get; }
  
  public ref int EntityIndexSelection { get; }


}