// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CSpriteOriented : CSprite, IConvertibleNativeHandle<CSpriteOriented> {

  static CSpriteOriented IConvertibleNativeHandle<CSpriteOriented>.From(nint handle) => new CSpriteOrientedImpl(handle);




}