// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CSSDSMsg_ViewTargetList : ISchemaClass {

  
  public SceneViewId_t ViewId { get; }
  
  public ref CUtlString ViewName { get; }
  
// CUtlVector< CSSDSMsg_ViewTarget >
  public ref CUtlVector Targets { get; }
}