// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CSSDSMsg_LayerBase : ISchemaClass<CSSDSMsg_LayerBase> {

  static CSSDSMsg_LayerBase ISchemaClass<CSSDSMsg_LayerBase>.From(nint handle) => new CSSDSMsg_LayerBaseImpl(handle);

  
  public SceneViewId_t ViewId { get; }
  
  public ref CUtlString ViewName { get; }
  
  public ref ulong LayerId { get; }
  
  public ref CUtlString LayerName { get; }
  
  public ref CUtlString DisplayText { get; }


}