// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CStateUpdateData : ISchemaClass {

  
  public ref CUtlString Name { get; }
  
  public AnimScriptHandle Script { get; }
  
  public ref CUtlVector<int> TransitionIndices { get; }
  
// CUtlVector< CStateActionUpdater >
  public ref CUtlVector Actions { get; }
  
  public AnimStateID StateID { get; }
  
  public SchemaUntypedField IsStartState { get; }
  
  public SchemaUntypedField IsEndState { get; }
  
  public SchemaUntypedField IsPassthrough { get; }
  
  public SchemaUntypedField IsPassthroughRootMotion { get; }
  
  public SchemaUntypedField PreEvaluatePassthroughTransitionPath { get; }


}