// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CStateActionUpdater : ISchemaClass, IConvertibleNativeHandle<CStateActionUpdater> {

  static CStateActionUpdater IConvertibleNativeHandle<CStateActionUpdater>.From(nint handle) => new CStateActionUpdaterImpl(handle);

  
  // CSmartPtr< CAnimActionUpdater >
  public SchemaUntypedField Action { get; }
  
  public ref StateActionBehavior Behavior { get; }


}