// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CSubtractUpdateNode : CBinaryUpdateNode {

  
  public ref BinaryNodeChildOption FootMotionTiming { get; }
  
  public ref bool ApplyToFootMotion { get; }
  
  public ref bool ApplyChannelsSeparately { get; }
  
  public ref bool UseModelSpace { get; }


}