// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CTankTargetChange : CPointEntity, IConvertibleNativeHandle<CTankTargetChange> {

  static CTankTargetChange IConvertibleNativeHandle<CTankTargetChange>.From(nint handle) => new CTankTargetChangeImpl(handle);

  
  // CVariantBase< CVariantDefaultAllocator >
  public SchemaUntypedField NewTarget { get; }
  
  public ref CUtlSymbolLarge NewTargetName { get; }


}