// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CTankTrainAI : CPointEntity, ISchemaClass<CTankTrainAI> {

  static CTankTrainAI ISchemaClass<CTankTrainAI>.From(nint handle) => new CTankTrainAIImpl(handle);

  
  public ref CHandle<CFuncTrackTrain> Train { get; }
  
  public ref CHandle<CBaseEntity> TargetEntity { get; }
  
  public ref int SoundPlaying { get; }
  
  public ref CUtlSymbolLarge StartSoundName { get; }
  
  public ref CUtlSymbolLarge EngineSoundName { get; }
  
  public ref CUtlSymbolLarge MovementSoundName { get; }
  
  public ref CUtlSymbolLarge TargetEntityName { get; }


}