// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CTestEffect : CBaseEntity {

  
  public ref int Loop { get; }
  
  public ref int Beam { get; }
  
  public SchemaUntypedField Beam1 { get; }
  
  public SchemaUntypedField BeamTime { get; }
  
  public GameTime_t StartTime { get; }


}