// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CTonemapController2 : CBaseEntity {

  
  public ref float AutoExposureMin { get; }
  
  public ref float AutoExposureMax { get; }
  
  public ref float ExposureAdaptationSpeedUp { get; }
  
  public ref float ExposureAdaptationSpeedDown { get; }
  
  public ref float TonemapEVSmoothingRange { get; }
}