// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CTonemapController2 : CBaseEntity {

  
  public ref float AutoExposureMin { get; }
  
  public ref float AutoExposureMax { get; }
  
  public ref float ExposureAdaptationSpeedUp { get; }
  
  public ref float ExposureAdaptationSpeedDown { get; }
  
  public ref float TonemapEVSmoothingRange { get; }

  public void AutoExposureMinUpdated();
  public void AutoExposureMaxUpdated();
  public void ExposureAdaptationSpeedUpUpdated();
  public void ExposureAdaptationSpeedDownUpdated();
  public void TonemapEVSmoothingRangeUpdated();
}