// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CTwistConstraint : CBaseConstraint {

  
  public ref bool Inverse { get; }
  
  public ref Quaternion ParentBindRotation { get; }
  
  public ref Quaternion ChildBindRotation { get; }


}