// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CVoiceContainerDecayingSineWave : CVoiceContainerBase {

  
  public ref float Frequency { get; }
  
  public ref float DecayTime { get; }


}