// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CVoiceContainerStaticAdditiveSynth__CGainScalePerInstance : ISchemaClass {

  
  public ref float MinVolume { get; }
  
  public ref int InstancesAtMinVolume { get; }
  
  public ref float MaxVolume { get; }
  
  public ref int InstancesAtMaxVolume { get; }
}