// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface DynamicVolumeDef_t : ISchemaClass, IConvertibleNativeHandle<DynamicVolumeDef_t> {

  static DynamicVolumeDef_t IConvertibleNativeHandle<DynamicVolumeDef_t>.From(nint handle) => new DynamicVolumeDef_tImpl(handle);

  
  public ref CHandle<CBaseEntity> Source { get; }
  
  public ref CHandle<CBaseEntity> Target { get; }
  
  public ref int HullIdx { get; }
  
  public ref Vector SourceAnchorPos { get; }
  
  public ref Vector TargetAnchorPos { get; }
  
  public ref uint AreaSrc { get; }
  
  public ref uint AreaDst { get; }
  
  public ref bool Attached { get; }


}