// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface EventClientPostOutput_t : ISchemaClass {

  
  public EngineLoopState_t LoopState { get; }
  
  public ref double RenderTime { get; }
  
  public ref float RenderFrameTime { get; }
  
  public ref float RenderFrameTimeUnbounded { get; }
  
  public ref bool RenderOnly { get; }


}