// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface EventServerProcessNetworking_t : EventSimulate_t, IConvertibleNativeHandle<EventServerProcessNetworking_t> {

  static EventServerProcessNetworking_t IConvertibleNativeHandle<EventServerProcessNetworking_t>.From(nint handle) => new EventServerProcessNetworking_tImpl(handle);




}