// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface FeAntiTunnelProbeBuild_t : ISchemaClass, IConvertibleNativeHandle<FeAntiTunnelProbeBuild_t> {

  static FeAntiTunnelProbeBuild_t IConvertibleNativeHandle<FeAntiTunnelProbeBuild_t>.From(nint handle) => new FeAntiTunnelProbeBuild_tImpl(handle);

  
  public ref float Weight { get; }
  
  public ref float ActivationDistance { get; }
  
  public ref float Bias { get; }
  
  public ref float Curvature { get; }
  
  public ref uint Flags { get; }
  
  public ref ushort ProbeNode { get; }
  
  public ref CUtlVector<ushort> TargetNodes { get; }


}