// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface FeBandBendLimit_t : ISchemaClass, IConvertibleNativeHandle<FeBandBendLimit_t> {

  static FeBandBendLimit_t IConvertibleNativeHandle<FeBandBendLimit_t>.From(nint handle) => new FeBandBendLimit_tImpl(handle);

  
  public ref float DistMin { get; }
  
  public ref float DistMax { get; }
  
  public ISchemaFixedArray<ushort> Node { get; }


}