// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface FeBuildBoxRigid_t : FeBoxRigid_t {

  
  public ref int Priority { get; }
  
  public ref uint VertexMapHash { get; }
  
  public ref uint AntitunnelGroupBits { get; }


}