// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface FeBuildSDFRigid_t : FeSDFRigid_t, IConvertibleNativeHandle<FeBuildSDFRigid_t> {

  static FeBuildSDFRigid_t IConvertibleNativeHandle<FeBuildSDFRigid_t>.From(nint handle) => new FeBuildSDFRigid_tImpl(handle);

  
  public ref int Priority { get; }
  
  public ref uint VertexMapHash { get; }
  
  public ref uint AntitunnelGroupBits { get; }


}