// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface FeRigidColliderIndices_t : ISchemaClass, IConvertibleNativeHandle<FeRigidColliderIndices_t> {

  static FeRigidColliderIndices_t IConvertibleNativeHandle<FeRigidColliderIndices_t>.From(nint handle) => new FeRigidColliderIndices_tImpl(handle);

  
  public ref ushort TaperedCapsuleRigidIndex { get; }
  
  public ref ushort SphereRigidIndex { get; }
  
  public ref ushort BoxRigidIndex { get; }
  
  public ref ushort SDFRigidIndex { get; }
  
  public ref ushort CollisionPlaneIndex { get; }


}