// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface FeTwistConstraint_t : ISchemaClass {

  
  public ref ushort NodeOrient { get; }
  
  public ref ushort NodeEnd { get; }
  
  public ref float TwistRelax { get; }
  
  public ref float SwingRelax { get; }


}