// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface FollowAttachmentSettings_t : ISchemaClass {

  
  public CAnimAttachment Attachment { get; }
  
  public ref int BoneIndex { get; }
  
  public AttachmentHandle_t AttachmentHandle { get; }
  
  public ref bool MatchTranslation { get; }
  
  public ref bool MatchRotation { get; }


}