// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface FootStepTrigger : ISchemaClass, IConvertibleNativeHandle<FootStepTrigger> {

  static FootStepTrigger IConvertibleNativeHandle<FootStepTrigger>.From(nint handle) => new FootStepTriggerImpl(handle);

  
  public ref CUtlVector<int> Tags { get; }
  
  public ref int FootIndex { get; }
  
  public ref StepPhase TriggerPhase { get; }


}