// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface FunctionInfo_t : ISchemaClass {

  
  public ref CUtlString Name { get; }
  
  public ref CUtlStringToken NameToken { get; }
  
  public ref int ParamCount { get; }
  
  public FuseFunctionIndex_t Index { get; }
  
  public ref bool IsPure { get; }


}