// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface IKTargetSettings_t : ISchemaClass {

  
  public ref IKTargetSource TargetSource { get; }
  
  public IKBoneNameAndIndex_t Bone { get; }
  
  public AnimParamID AnimgraphParameterNamePosition { get; }
  
  public AnimParamID AnimgraphParameterNameOrientation { get; }
  
  public ref IKTargetCoordinateSystem TargetCoordSystem { get; }


}