// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface magnetted_objects_t : ISchemaClass<magnetted_objects_t> {

  static magnetted_objects_t ISchemaClass<magnetted_objects_t>.From(nint handle) => new magnetted_objects_tImpl(handle);

  
  public ref CHandle<CBaseEntity> Entity { get; }


}