// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface ManifestTestResource_t : ISchemaClass, IConvertibleNativeHandle<ManifestTestResource_t> {

  static ManifestTestResource_t IConvertibleNativeHandle<ManifestTestResource_t>.From(nint handle) => new ManifestTestResource_tImpl(handle);

  
  public ref CUtlString Name { get; }
  
  public ref CStrongHandle<InfoForResourceTypeManifestTestResource_t> Child { get; }


}