// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface MaterialVariable_t : ISchemaClass {

  
  public ref CUtlString StrVariable { get; }
  
  public ParticleAttributeIndex_t VariableField { get; }
  
  public ref float Scale { get; }


}