// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface ModelEmbeddedMesh_t : ISchemaClass<ModelEmbeddedMesh_t> {

  static ModelEmbeddedMesh_t ISchemaClass<ModelEmbeddedMesh_t>.From(nint handle) => new ModelEmbeddedMesh_tImpl(handle);
  static int ISchemaClass<ModelEmbeddedMesh_t>.Size => 112;

  
  public string Name { get; set; }
  
  public ref int MeshIndex { get; }
  
  public ref int DataBlock { get; }
  
  public ref int MorphBlock { get; }
  
  // CUtlVector< ModelMeshBufferData_t >
  public ref CUtlVector VertexBuffers { get; }
  
  // CUtlVector< ModelMeshBufferData_t >
  public ref CUtlVector IndexBuffers { get; }
  
  // CUtlVector< ModelMeshBufferData_t >
  public ref CUtlVector ToolsBuffers { get; }
  
  public ref int VBIBBlock { get; }
  
  public ref int ToolsVBBlock { get; }


}