// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface ParamSpanSample_t : ISchemaClass {

  
  public SchemaUntypedField Value { get; }
  
  public ref float Cycle { get; }


}