// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface ParticleChildrenInfo_t : ISchemaClass {

  
  public ref CStrongHandle<InfoForResourceTypeIParticleSystemDefinition> ChildRef { get; }
  
  public ref float Delay { get; }
  
  public ref bool EndCap { get; }
  
  public ref bool DisableChild { get; }
  
  public ref ParticleDetailLevel_t DetailLevel { get; }


}