// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface PhysicsParticleId_t : ISchemaClass, IConvertibleNativeHandle<PhysicsParticleId_t> {

  static PhysicsParticleId_t IConvertibleNativeHandle<PhysicsParticleId_t>.From(nint handle) => new PhysicsParticleId_tImpl(handle);

  
  public ref uint Value { get; }


}