// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface PointDefinition_t : ISchemaClass<PointDefinition_t> {

  static PointDefinition_t ISchemaClass<PointDefinition_t>.From(nint handle) => new PointDefinition_tImpl(handle);

  
  public ref int ControlPoint { get; }
  
  public ref bool LocalCoords { get; }
  
  public ref Vector Offset { get; }


}