// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface PointCameraSettings_t : ISchemaClass {

  
  public ref float NearBlurryDistance { get; }
  
  public ref float NearCrispDistance { get; }
  
  public ref float FarCrispDistance { get; }
  
  public ref float FarBlurryDistance { get; }


}