// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface PostProcessingFogScatteringParameters_t : ISchemaClass, IConvertibleNativeHandle<PostProcessingFogScatteringParameters_t> {

  static PostProcessingFogScatteringParameters_t IConvertibleNativeHandle<PostProcessingFogScatteringParameters_t>.From(nint handle) => new PostProcessingFogScatteringParameters_tImpl(handle);

  
  public ref float Radius { get; }
  
  public ref float Scale { get; }
  
  public ref float CubemapScale { get; }
  
  public ref float VolumetricScale { get; }
  
  public ref float GradientScale { get; }


}