// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface PredictedDamageTag_t : ISchemaClass, IConvertibleNativeHandle<PredictedDamageTag_t> {

  static PredictedDamageTag_t IConvertibleNativeHandle<PredictedDamageTag_t>.From(nint handle) => new PredictedDamageTag_tImpl(handle);

  
  public GameTick_t TagTick { get; }
  
  public ref float FlinchModSmall { get; }
  
  public ref float FlinchModLarge { get; }
  
  public ref float FriendlyFireDamageReductionRatio { get; }

  public void TagTickUpdated();
  public void FlinchModSmallUpdated();
  public void FlinchModLargeUpdated();
  public void FriendlyFireDamageReductionRatioUpdated();
}