// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface PulseRuntimeRegisterIndex_t : ISchemaClass, IConvertibleNativeHandle<PulseRuntimeRegisterIndex_t> {

  static PulseRuntimeRegisterIndex_t IConvertibleNativeHandle<PulseRuntimeRegisterIndex_t>.From(nint handle) => new PulseRuntimeRegisterIndex_tImpl(handle);

  
  public ref short Value { get; }


}