// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface PulseDocNodeID_t : ISchemaClass {

  
  public ref int Value { get; }
}