// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface RnFace_t : ISchemaClass, IConvertibleNativeHandle<RnFace_t> {

  static RnFace_t IConvertibleNativeHandle<RnFace_t>.From(nint handle) => new RnFace_tImpl(handle);

  
  public ref byte Edge { get; }


}