// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface RnSoftbodySpring_t : ISchemaClass {

  
  public ISchemaFixedArray<ushort> Particle { get; }
  
  public ref float Length { get; }


}