// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface RotatorQueueEntry_t : ISchemaClass {

  
  public ref Quaternion Target { get; }
  
  public ref RotatorTargetSpace_t Space { get; }
}