// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface RotatorHistoryEntry_t : ISchemaClass {

  
  public ref Quaternion InvChange { get; }
  
  public GameTime_t TimeRotationStart { get; }


}