// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface SequenceHistory_t : ISchemaClass {

  
  public HSequence Sequence { get; }
  
  public GameTime_t SeqStartTime { get; }
  
  public ref float SeqFixedCycle { get; }
  
  public ref AnimLoopMode_t SeqLoopMode { get; }
  
  public ref float PlaybackRate { get; }
  
  public ref float CyclesPerSecond { get; }


}