// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface SoundeventPathCornerPairNetworked_t : ISchemaClass {

  
  public ref Vector P1 { get; }
  
  public ref Vector P2 { get; }
  
  public ref float PathLengthSqr { get; }
  
  public ref float P1Pct { get; }
  
  public ref float P2Pct { get; }

  public void P1Updated();
  public void P2Updated();
  public void PathLengthSqrUpdated();
  public void P1PctUpdated();
  public void P2PctUpdated();
}