// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface SpawnPoint : CServerOnlyPointEntity, IConvertibleNativeHandle<SpawnPoint> {

  static SpawnPoint IConvertibleNativeHandle<SpawnPoint>.From(nint handle) => new SpawnPointImpl(handle);

  
  public ref int Priority { get; }
  
  public ref bool Enabled { get; }
  
  public ref int Type { get; }


}