// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface VMixPitchShiftDesc_t : ISchemaClass {

  
  public ref int GrainSampleCount { get; }
  
  public ref float PitchShift { get; }
  
  public ref int Quality { get; }
  
  public ref int ProcType { get; }


}