// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface VMixAutoFilterDesc_t : ISchemaClass {

  
  public ref float EnvelopeAmount { get; }
  
  public ref float AttackTimeMS { get; }
  
  public ref float ReleaseTimeMS { get; }
  
  public VMixFilterDesc_t Filter { get; }
  
  public ref float LFOAmount { get; }
  
  public ref float LFORate { get; }
  
  public ref float Phase { get; }
  
  public ref VMixLFOShape_t LFOShape { get; }


}