// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface VsInputSignatureElement_t : ISchemaClass<VsInputSignatureElement_t> {

  static VsInputSignatureElement_t ISchemaClass<VsInputSignatureElement_t>.From(nint handle) => new VsInputSignatureElement_tImpl(handle);

  
  public ISchemaFixedString Name { get; }
  
  public ISchemaFixedString Semantic { get; }
  
  public ISchemaFixedString D3DSemanticName { get; }
  
  public ref int D3DSemanticIndex { get; }


}