// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface WaterWheelFrictionScale_t : ISchemaClass {

  
  public ref float FractionOfWheelSubmerged { get; }
  
  public ref float FrictionScale { get; }


}