// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_SetControlPointOrientationToCPVelocity : CParticleFunctionPreEmission {

  
  public ref int CPInput { get; }
  
  public ref int CPOutput { get; }
}