// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_GlobalLight : CParticleFunctionOperator {

  
  public ref float Scale { get; }
  
  public ref bool ClampLowerRange { get; }
  
  public ref bool ClampUpperRange { get; }
}