// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_LocalAccelerationForce : CParticleFunctionForce {

  
  public ref int CP { get; }
  
  public ref int ScaleCP { get; }
  
  public CParticleCollectionVecInput Accel { get; }
}