// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CBoneConstraintDotToMorph : CBoneConstraintBase {

  
  public ref CUtlString BoneName { get; }
  
  public ref CUtlString TargetBoneName { get; }
  
  public ref CUtlString MorphChannelName { get; }
  
  public ISchemaFixedArray<float> Remap { get; }
}