// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CCSPlayerController_ActionTrackingServices : CPlayerControllerComponent {

  
// CUtlVectorEmbeddedNetworkVar< CSPerRoundStats_t >
  public ref CUtlVector PerRoundStats { get; }
  
  public CSMatchStats_t MatchStats { get; }
  
  public ref int NumRoundKills { get; }
  
  public ref int NumRoundKillsHeadshots { get; }
  
  public ref uint TotalRoundDamageDealt { get; }
}