// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CFuncNavObstruction : CBaseModelEntity {

  
  public ref bool Disabled { get; }
  
  public ref bool UseAsyncObstacleUpdate { get; }
}