// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CKeepUpright : CPointEntity {

  
  public ref Vector WorldGoalAxis { get; }
  
  public ref Vector LocalTestAxis { get; }
  
  public ref CUtlSymbolLarge NameAttach { get; }
  
  public ref CHandle<CBaseEntity> AttachedObject { get; }
  
  public ref float AngularLimit { get; }
  
  public ref bool Active { get; }
  
  public ref bool DampAllRotation { get; }
}