// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CLogicGameEvent : CLogicalEntity {

  
  public ref CUtlSymbolLarge EventName { get; }
}