// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CMorphData : ISchemaClass {

  
  public ref CUtlString Name { get; }
  
// CUtlVector< CMorphRectData >
  public ref CUtlVector MorphRectDatas { get; }
}