// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNewParticleEffect : IParticleEffect {

  
  public CNewParticleEffect Next { get; }
  
  public CNewParticleEffect Prev { get; }
  
  public IParticleCollection Particles { get; }
  
  public ref CString DebugName { get; }
  
  public SchemaUntypedField DontRemove { get; }
  
  public SchemaUntypedField Remove { get; }
  
  public SchemaUntypedField NeedsBBoxUpdate { get; }
  
  public SchemaUntypedField IsFirstFrame { get; }
  
  public SchemaUntypedField AutoUpdateBBox { get; }
  
  public SchemaUntypedField Allocated { get; }
  
  public SchemaUntypedField Simulate { get; }
  
  public SchemaUntypedField ShouldPerformCullCheck { get; }
  
  public SchemaUntypedField ForceNoDraw { get; }
  
  public SchemaUntypedField SuppressScreenSpaceEffect { get; }
  
  public SchemaUntypedField ShouldSave { get; }
  
  public SchemaUntypedField ShouldSimulateDuringGamePaused { get; }
  
  public SchemaUntypedField ShouldCheckFoW { get; }
  
  public ref Vector SortOrigin { get; }
  
  public ref float Scale { get; }
  
  public PARTICLE_EHANDLE__ Owner { get; }
  
  public CParticleProperty OwningParticleProperty { get; }
  
  public ref float FreezeTransitionStart { get; }
  
  public ref float FreezeTransitionDuration { get; }
  
  public ref float FreezeTransitionOverride { get; }
  
  public ref bool FreezeTransitionActive { get; }
  
  public ref bool FreezeTargetState { get; }
  
  public ref bool CanFreeze { get; }
  
  public ref Vector LastMin { get; }
  
  public ref Vector LastMax { get; }
  
  public ref uint SplitScreenUser { get; }
  
  public ref Vector AggregationCenter { get; }
  
  public ref int RefCount { get; }
}