// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmClipNode__CDefinition : CNmClipReferenceNode__CDefinition {

  
  public ref short PlayInReverseValueNodeIdx { get; }
  
  public ref short ResetTimeValueNodeIdx { get; }
  
  public ref float SpeedMultiplier { get; }
  
  public ref int StartSyncEventOffset { get; }
  
  public ref bool SampleRootMotion { get; }
  
  public ref bool AllowLooping { get; }
  
  public ref short DataSlotIdx { get; }
}