// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmFloatRemapNode__RemapRange_t : ISchemaClass {

  
  public ref float Begin { get; }
  
  public ref float End { get; }
}