// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CParticleFunctionEmitter : CParticleFunction {

  
  public ref int EmitterIndex { get; }
}