// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CParticleVariableRef : ISchemaClass {

  
  public SchemaUntypedField VariableName { get; }
  
  public ref PulseValueType_t VariableType { get; }
}