// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPulseCell_Test_MultiOutflow_WithParams_Yielding : CPulseCell_BaseYieldingInflow {

  
  public SignatureOutflow_Continue Out1 { get; }
  
  public SignatureOutflow_Continue AsyncChild1 { get; }
  
  public SignatureOutflow_Continue AsyncChild2 { get; }
  
  public SignatureOutflow_Resume YieldResume1 { get; }
  
  public SignatureOutflow_Resume YieldResume2 { get; }
}