// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CRemapValueComponentUpdater : CAnimComponentUpdater {

  
// CUtlVector< CRemapValueUpdateItem >
  public ref CUtlVector Items { get; }
}