// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CTakeDamageResult : ISchemaClass {

  
  public CTakeDamageInfo OriginatingInfo { get; }
  
  public ref int HealthLost { get; }
  
  public ref int DamageTaken { get; }
  
  public ref float PreModifiedDamage { get; }
  
  public ref int TotalledHealthLost { get; }
  
  public ref int TotalledDamageDealt { get; }
}