// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CTeam : CBaseEntity {

  
  public ref CUtlVector<CHandle<CBasePlayerController>> PlayerControllers { get; }
  
  public ref CUtlVector<CHandle<CBasePlayerPawn>> Players { get; }
  
  public ref int Score { get; }
  
  public ISchemaFixedString Teamname { get; }
}