// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CWeaponBaseItem : CCSWeaponBase {

  
  public ref bool SequenceInProgress { get; }
  
  public ref bool Redraw { get; }
}