// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface FeSDFRigid_t : ISchemaClass {

  
  public ref Vector LocalMin { get; }
  
  public ref Vector LocalMax { get; }
  
  public ref float Bounciness { get; }
  
  public ref ushort Node { get; }
  
  public ref ushort CollisionMask { get; }
  
  public ref ushort VertexMapIndex { get; }
  
  public ref ushort Flags { get; }
  
  public ref CUtlVector<float> Distances { get; }
  
  public ref int Width { get; }
  
  public ref int Height { get; }
  
  public ref int Depth { get; }
}