// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface FeWeightedNode_t : ISchemaClass {

  
  public ref ushort Node { get; }
  
  public ref ushort Weight { get; }
}