// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface FollowTargetOpFixedSettings_t : ISchemaClass {

  
  public ref int BoneIndex { get; }
  
  public ref bool BoneTarget { get; }
  
  public ref int BoneTargetIndex { get; }
  
  public ref bool WorldCoodinateTarget { get; }
  
  public ref bool MatchTargetOrientation { get; }
}