// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface GameAmmoTypeInfo_t : AmmoTypeInfo_t {

  
  public ref int BuySize { get; }
  
  public ref int Cost { get; }
}