// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface sky3dparams_t : ISchemaClass {

  
  public ref short Scale { get; }
  
  public ref Vector Origin { get; }
  
  public ref bool Clip3DSkyBoxNearToWorldFar { get; }
  
  public ref float Clip3DSkyBoxNearToWorldFarOffset { get; }
  
  public fogparams_t Fog { get; }
  
  public ref uint WorldGroupID { get; }
}