// <auto-generated />

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface VMixShaperDesc_t : ISchemaClass {

  
  public ref int Shape { get; }
  
  public ref float FldbDrive { get; }
  
  public ref float FldbOutputGain { get; }
  
  public ref float WetMix { get; }
  
  public ref int OversampleFactor { get; }
}