// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class AnimationSnapshot_tImpl : AnimationSnapshotBase_tImpl, AnimationSnapshot_t {

  public AnimationSnapshot_tImpl(nint handle) : base(handle) {
  }

  public ref int EntIndex {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0xAC640D3E5558C54A));
  }
  public ref CUtlString ModelName {
    get => ref _Handle.AsRef<CUtlString>(Schema.GetOffset(0xAC640D3E5D35B6E1));
  }


}