// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_INIT_VelocityRandomImpl : CParticleFunctionInitializerImpl, C_INIT_VelocityRandom {

  public C_INIT_VelocityRandomImpl(nint handle) : base(handle) {
  }

  public ref int ControlPointNumber {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0xFCCBA9E3F31A6BD));
  }
  public CPerParticleFloatInput SpeedMin {
    get => new CPerParticleFloatInputImpl(_Handle + Schema.GetOffset(0xFCCBA9EB989E1F8));
  }
  public CPerParticleFloatInput SpeedMax {
    get => new CPerParticleFloatInputImpl(_Handle + Schema.GetOffset(0xFCCBA9ECF9D8C52));
  }
  public CPerParticleVecInput LocalCoordinateSystemSpeedMin {
    get => new CPerParticleVecInputImpl(_Handle + Schema.GetOffset(0xFCCBA9EA4A0F1AE));
  }
  public CPerParticleVecInput LocalCoordinateSystemSpeedMax {
    get => new CPerParticleVecInputImpl(_Handle + Schema.GetOffset(0xFCCBA9E968D53EC));
  }
  public ref bool IgnoreDT {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0xFCCBA9E530C3863));
  }
  public CRandomNumberGeneratorParameters RandomnessParameters {
    get => new CRandomNumberGeneratorParametersImpl(_Handle + Schema.GetOffset(0xFCCBA9E7EDF50AD));
  }


}