// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_INIT_RandomAlphaWindowThresholdImpl : CParticleFunctionInitializerImpl, C_INIT_RandomAlphaWindowThreshold {

  public C_INIT_RandomAlphaWindowThresholdImpl(nint handle) : base(handle) {
  }

  public ref float Min {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x68DB6A2E3B1A5649));
  }
  public ref float Max {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x68DB6A2E2D06B887));
  }
  public ref float Exponent {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x68DB6A2E20A7BCBC));
  }


}