// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_EnableChildrenFromParentParticleCountImpl : CParticleFunctionPreEmissionImpl, C_OP_EnableChildrenFromParentParticleCount {

  public C_OP_EnableChildrenFromParentParticleCountImpl(nint handle) : base(handle) {
  }

  public ref int ChildGroupID {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0xDF13D5F2E3F3C965));
  }
  public ref int FirstChild {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0xDF13D5F22DF4A8BD));
  }
  public CParticleCollectionFloatInput NumChildrenToEnable {
    get => new CParticleCollectionFloatInputImpl(_Handle + Schema.GetOffset(0xDF13D5F28039247A));
  }
  public ref bool DisableChildren {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0xDF13D5F2F13DBFCC));
  }
  public ref bool PlayEndcapOnStop {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0xDF13D5F2CEC82FA1));
  }
  public ref bool DestroyImmediately {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0xDF13D5F275F43101));
  }


}