// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_CollideWithParentParticlesImpl : CParticleFunctionConstraintImpl, C_OP_CollideWithParentParticles {

  public C_OP_CollideWithParentParticlesImpl(nint handle) : base(handle) {
  }

  public CPerParticleFloatInput ParentRadiusScale {
    get => new CPerParticleFloatInputImpl(_Handle + Schema.GetOffset(0x73030DD0CD77EF69));
  }
  public CPerParticleFloatInput RadiusScale {
    get => new CPerParticleFloatInputImpl(_Handle + Schema.GetOffset(0x73030DD0A7A20159));
  }


}