// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_ScreenSpaceRotateTowardTargetImpl : CParticleFunctionOperatorImpl, C_OP_ScreenSpaceRotateTowardTarget {

  public C_OP_ScreenSpaceRotateTowardTargetImpl(nint handle) : base(handle) {
  }

  public CPerParticleVecInput TargetPosition {
    get => new CPerParticleVecInputImpl(_Handle + Schema.GetOffset(0xD66164FC554C563B));
  }
  public CParticleRemapFloatInput OutputRemap {
    get => new CParticleRemapFloatInputImpl(_Handle + Schema.GetOffset(0xD66164FC1239396F));
  }
  public ref ParticleSetMethod_t SetMethod {
    get => ref _Handle.AsRef<ParticleSetMethod_t>(Schema.GetOffset(0xD66164FCFB53C31E));
  }
  public CPerParticleFloatInput ScreenEdgeAlignmentDistance {
    get => new CPerParticleFloatInputImpl(_Handle + Schema.GetOffset(0xD66164FCDB3D3EAC));
  }


}