// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_LerpEndCapVectorImpl : CParticleFunctionOperatorImpl, C_OP_LerpEndCapVector {

  public C_OP_LerpEndCapVectorImpl(nint handle) : base(handle) {
  }

  public ParticleAttributeIndex_t FieldOutput {
    get => new ParticleAttributeIndex_tImpl(_Handle + Schema.GetOffset(0x4847E160E5729606));
  }
  public ref Vector Output {
    get => ref _Handle.AsRef<Vector>(Schema.GetOffset(0x4847E16008B7FF64));
  }
  public ref float LerpTime {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x4847E16054FD987F));
  }


}