// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_DifferencePreviousParticleImpl : CParticleFunctionOperatorImpl, C_OP_DifferencePreviousParticle {

  public C_OP_DifferencePreviousParticleImpl(nint handle) : base(handle) {
  }

  public ParticleAttributeIndex_t FieldInput {
    get => new ParticleAttributeIndex_tImpl(_Handle + Schema.GetOffset(0xD626A7A9AE775669));
  }
  public ParticleAttributeIndex_t FieldOutput {
    get => new ParticleAttributeIndex_tImpl(_Handle + Schema.GetOffset(0xD626A7A9E5729606));
  }
  public ref float InputMin {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0xD626A7A9E88A0D0F));
  }
  public ref float InputMax {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0xD626A7A9D6766901));
  }
  public ref float OutputMin {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0xD626A7A95F8D7716));
  }
  public ref float OutputMax {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0xD626A7A951A0E8C4));
  }
  public ref ParticleSetMethod_t SetMethod {
    get => ref _Handle.AsRef<ParticleSetMethod_t>(Schema.GetOffset(0xD626A7A9FB53C31E));
  }
  public ref bool ActiveRange {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0xD626A7A93FA53B84));
  }
  public ref bool SetPreviousParticle {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0xD626A7A9BDC03798));
  }


}