// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_ChooseRandomChildrenInGroupImpl : CParticleFunctionPreEmissionImpl, C_OP_ChooseRandomChildrenInGroup {

  public C_OP_ChooseRandomChildrenInGroupImpl(nint handle) : base(handle) {
  }

  public ref int ChildGroupID {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0xF79CD816E3F3C965));
  }
  public CParticleCollectionFloatInput NumberOfChildren {
    get => new CParticleCollectionFloatInputImpl(_Handle + Schema.GetOffset(0xF79CD8160275D868));
  }


}