// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_SetControlPointToHandImpl : CParticleFunctionPreEmissionImpl, C_OP_SetControlPointToHand {

  public C_OP_SetControlPointToHandImpl(nint handle) : base(handle) {
  }

  public ref int CP1 {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0x5D527B26D4B1E579));
  }
  public ref int Hand {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0x5D527B26D49ECB4C));
  }
  public ref Vector CP1Pos {
    get => ref _Handle.AsRef<Vector>(Schema.GetOffset(0x5D527B26408288D9));
  }
  public ref bool OrientToHand {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0x5D527B26372CF7D8));
  }


}