// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_RenderDeferredLightImpl : CParticleFunctionRendererImpl, C_OP_RenderDeferredLight {

  public C_OP_RenderDeferredLightImpl(nint handle) : base(handle) {
  }

  public ref bool UseAlphaTestWindow {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0x44291266951B0D10));
  }
  public ref bool UseTexture {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0x4429126624A2D28F));
  }
  public ref float RadiusScale {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x44291266A7A20159));
  }
  public ref float AlphaScale {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x44291266EC6D3C25));
  }
  public ParticleAttributeIndex_t Alpha2Field {
    get => new ParticleAttributeIndex_tImpl(_Handle + Schema.GetOffset(0x44291266F60EADC1));
  }
  public CParticleCollectionVecInput ColorScale {
    get => new CParticleCollectionVecInputImpl(_Handle + Schema.GetOffset(0x442912669F9BB8BA));
  }
  public ref ParticleColorBlendType_t ColorBlendType {
    get => ref _Handle.AsRef<ParticleColorBlendType_t>(Schema.GetOffset(0x44291266DBC6EFCF));
  }
  public ref float LightDistance {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x44291266FAE1FD66));
  }
  public ref float StartFalloff {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x44291266A8F25925));
  }
  public ref float DistanceFalloff {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x44291266A9C33036));
  }
  public ref float SpotFoV {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x44291266D202E536));
  }
  public ParticleAttributeIndex_t AlphaTestPointField {
    get => new ParticleAttributeIndex_tImpl(_Handle + Schema.GetOffset(0x442912666AD21C15));
  }
  public ParticleAttributeIndex_t AlphaTestRangeField {
    get => new ParticleAttributeIndex_tImpl(_Handle + Schema.GetOffset(0x442912663E3E66D4));
  }
  public ParticleAttributeIndex_t AlphaTestSharpnessField {
    get => new ParticleAttributeIndex_tImpl(_Handle + Schema.GetOffset(0x44291266BCB74B82));
  }
  public ref CStrongHandle<InfoForResourceTypeCTextureBase> Texture {
    get => ref _Handle.AsRef<CStrongHandle<InfoForResourceTypeCTextureBase>>(Schema.GetOffset(0x442912668C0A2FB6));
  }
  public ref int HSVShiftControlPoint {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0x442912668848C01F));
  }


}