// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_FadeOutSimpleImpl : CParticleFunctionOperatorImpl, C_OP_FadeOutSimple {

  public C_OP_FadeOutSimpleImpl(nint handle) : base(handle) {
  }

  public ref float FadeOutTime {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0xD439658FE86D2FC2));
  }
  public ParticleAttributeIndex_t FieldOutput {
    get => new ParticleAttributeIndex_tImpl(_Handle + Schema.GetOffset(0xD439658FE5729606));
  }


}