// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAimConstraintImpl : CBaseConstraintImpl, CAimConstraint {

  public CAimConstraintImpl(nint handle) : base(handle) {
  }

  public ref Quaternion AimOffset {
    get => ref _Handle.AsRef<Quaternion>(Schema.GetOffset(0x6C67AB6C43737FEA));
  }
  public ref uint UpType {
    get => ref _Handle.AsRef<uint>(Schema.GetOffset(0x6C67AB6C038EA2BC));
  }


}