// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAnimGraphModelBindingImpl : SchemaClass, CAnimGraphModelBinding {

  public CAnimGraphModelBindingImpl(nint handle) : base(handle) {
  }

  public string ModelName {
    get {
      var ptr = _Handle.Read<nint>(Schema.GetOffset(0xC0F296335D35B6E1));
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, 0xC0F296335D35B6E1, value);
  } 
  public SchemaUntypedField SharedData {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0xC0F29633D0085FE6));
  }


}