// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAnimParamHandleImpl : SchemaClass, CAnimParamHandle {

  public CAnimParamHandleImpl(nint handle) : base(handle) {
  }

  public ref AnimParamType_t Type {
    get => ref _Handle.AsRef<AnimParamType_t>(Schema.GetOffset(0x7B9461E0F04B4ED));
  }
  public ref byte Index {
    get => ref _Handle.AsRef<byte>(Schema.GetOffset(0x7B9461E491963CB));
  }


}