// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAnimUpdateSharedDataImpl : SchemaClass, CAnimUpdateSharedData {

  public CAnimUpdateSharedDataImpl(nint handle) : base(handle) {
  }

  public ref CUtlVector Nodes {
    get => ref _Handle.AsRef<CUtlVector>(Schema.GetOffset(0xA294DB47780F027A));
  }
  public SchemaUntypedField NodeIndexMap {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0xA294DB47D3B3E7A3));
  }
  public ref CUtlVector Components {
    get => ref _Handle.AsRef<CUtlVector>(Schema.GetOffset(0xA294DB47F87FC409));
  }
  public SchemaUntypedField ParamListUpdater {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0xA294DB4784AA7F15));
  }
  public SchemaUntypedField TagManagerUpdater {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0xA294DB47432E460D));
  }
  public SchemaUntypedField ScriptManager {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0xA294DB47F4257D31));
  }
  public CAnimGraphSettingsManager Settings {
    get => new CAnimGraphSettingsManagerImpl(_Handle + Schema.GetOffset(0xA294DB47B3DE33A8));
  }
  public SchemaUntypedField StaticPoseCache {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0xA294DB475BFC0C1E));
  }
  public SchemaUntypedField Skeleton {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0xA294DB4744BBF688));
  }
  public CAnimNodePath RootNodePath {
    get => new CAnimNodePathImpl(_Handle + Schema.GetOffset(0xA294DB476893B9EE));
  }


}