// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAnimScriptComponentUpdaterImpl : CAnimComponentUpdaterImpl, CAnimScriptComponentUpdater {

  public CAnimScriptComponentUpdaterImpl(nint handle) : base(handle) {
  }

  public AnimScriptHandle Script {
    get => new AnimScriptHandleImpl(_Handle + Schema.GetOffset(0x2BD2101829D70FB0));
  }


}