// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAnimationGraphVisualizerSphereImpl : CAnimationGraphVisualizerPrimitiveBaseImpl, CAnimationGraphVisualizerSphere {

  public CAnimationGraphVisualizerSphereImpl(nint handle) : base(handle) {
  }

  public ref Vector WsPosition {
    get => ref _Handle.AsRef<Vector>(Schema.GetOffset(0x85D725BDCA77AB88));
  }
  public ref float Radius {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x85D725BD5ACFC08D));
  }
  public ref Color Color {
    get => ref _Handle.AsRef<Color>(Schema.GetOffset(0x85D725BDD7D017D8));
  }


}