// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAnimationGraphVisualizerTextImpl : CAnimationGraphVisualizerPrimitiveBaseImpl, CAnimationGraphVisualizerText {

  public CAnimationGraphVisualizerTextImpl(nint handle) : base(handle) {
  }

  public ref Vector WsPosition {
    get => ref _Handle.AsRef<Vector>(Schema.GetOffset(0x123E08CFCA77AB88));
  }
  public ref Color Color {
    get => ref _Handle.AsRef<Color>(Schema.GetOffset(0x123E08CFD7D017D8));
  }
  public ref CUtlString Text {
    get => ref _Handle.AsRef<CUtlString>(Schema.GetOffset(0x123E08CFFB9532BE));
  }


}