// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAudioAnimTagImpl : CAnimTagBaseImpl, CAudioAnimTag {

  public CAudioAnimTagImpl(nint handle) : base(handle) {
  }

  public ref CUtlString ClipName {
    get => ref _Handle.AsRef<CUtlString>(Schema.GetOffset(0x785914777D84420));
  }
  public ref CUtlString AttachmentName {
    get => ref _Handle.AsRef<CUtlString>(Schema.GetOffset(0x7859147295DA9CB));
  }
  public ref float Volume {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x78591477647E0C9));
  }
  public ref bool StopWhenTagEnds {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0x7859147878BB46D));
  }
  public ref bool StopWhenGraphEnds {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0x785914705444061));
  }
  public ref bool PlayOnServer {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0x7859147BAA179F9));
  }
  public ref bool PlayOnClient {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0x78591471136791D));
  }


}