// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CBtActionMoveToImpl : CBtNodeImpl, CBtActionMoveTo {

  public CBtActionMoveToImpl(nint handle) : base(handle) {
  }

  public string DestinationInputKey {
    get {
      var ptr = _Handle.Read<nint>(Schema.GetOffset(0xD3E75386EA98FEAB));
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, 0xD3E75386EA98FEAB, value);
  } 
  public string HidingSpotInputKey {
    get {
      var ptr = _Handle.Read<nint>(Schema.GetOffset(0xD3E75386B3449D70));
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, 0xD3E75386B3449D70, value);
  } 
  public string ThreatInputKey {
    get {
      var ptr = _Handle.Read<nint>(Schema.GetOffset(0xD3E75386E8FD875B));
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, 0xD3E75386E8FD875B, value);
  } 
  public ref Vector Destination {
    get => ref _Handle.AsRef<Vector>(Schema.GetOffset(0xD3E753868964CB9F));
  }
  public ref bool AutoLookAdjust {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0xD3E75386CC24EFB6));
  }
  public ref bool ComputePath {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0xD3E75386E6332AE9));
  }
  public ref float DamagingAreasPenaltyCost {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0xD3E753868B6813F3));
  }
  public CountdownTimer CheckApproximateCornersTimer {
    get => new CountdownTimerImpl(_Handle + Schema.GetOffset(0xD3E7538689360D84));
  }
  public CountdownTimer CheckHighPriorityItem {
    get => new CountdownTimerImpl(_Handle + Schema.GetOffset(0xD3E7538619EE60B4));
  }
  public CountdownTimer RepathTimer {
    get => new CountdownTimerImpl(_Handle + Schema.GetOffset(0xD3E753866BF3B99C));
  }
  public ref float ArrivalEpsilon {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0xD3E75386193730DE));
  }
  public ref float AdditionalArrivalEpsilon2D {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0xD3E7538601105845));
  }
  public ref float HidingSpotCheckDistanceThreshold {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0xD3E75386BA171B2E));
  }
  public ref float NearestAreaDistanceThreshold {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0xD3E75386C5DEF260));
  }


}