// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CCopyRecipientFilterImpl : SchemaClass, CCopyRecipientFilter {

  public CCopyRecipientFilterImpl(nint handle) : base(handle) {
  }

  public ref int Flags {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0xB27F546C36B92FAC));
  }
  public ref CUtlVector<uint> Recipients {
    get => ref _Handle.AsRef<CUtlVector<uint>>(Schema.GetOffset(0xB27F546CDF6522D1));
  }


}