// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CCSGameModeRules_ArmsRaceImpl : CCSGameModeRulesImpl, CCSGameModeRules_ArmsRace {

  public CCSGameModeRules_ArmsRaceImpl(nint handle) : base(handle) {
  }

  public ref CUtlVector<CUtlString> WeaponSequence {
    get => ref _Handle.AsRef<CUtlVector<CUtlString>>(Schema.GetOffset(0xDFFFC2FB1426444C));
  }

  public void WeaponSequenceUpdated() {
    Schema.Update(_Handle, 0xDFFFC2FB1426444C);
  }
}