// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CCSPlaceImpl : CServerOnlyModelEntityImpl, CCSPlace {

  public CCSPlaceImpl(nint handle) : base(handle) {
  }

  public string Name {
    get {
      var ptr = _Handle.Read<nint>(Schema.GetOffset(0x7AF35BE34D8F5786));
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, 0x7AF35BE34D8F5786, value);
  } 


}