// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CCSPlayer_UseServicesImpl : CPlayer_UseServicesImpl, CCSPlayer_UseServices {

  public CCSPlayer_UseServicesImpl(nint handle) : base(handle) {
  }

  public ref CHandle<CBaseEntity> LastKnownUseEntity {
    get => ref _Handle.AsRef<CHandle<CBaseEntity>>(Schema.GetOffset(0xE5F718912806F946));
  }
  public GameTime_t LastUseTimeStamp {
    get => new GameTime_tImpl(_Handle + Schema.GetOffset(0xE5F7189104BF376E));
  }
  public GameTime_t TimeLastUsedWindow {
    get => new GameTime_tImpl(_Handle + Schema.GetOffset(0xE5F7189165762AEB));
  }


}