// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CDamageRecordImpl : SchemaClass, CDamageRecord {

  public CDamageRecordImpl(nint handle) : base(handle) {
  }

  public ref CHandle<CCSPlayerPawn> PlayerDamager {
    get => ref _Handle.AsRef<CHandle<CCSPlayerPawn>>(Schema.GetOffset(0x149283162F5812D9));
  }
  public ref CHandle<CCSPlayerPawn> PlayerRecipient {
    get => ref _Handle.AsRef<CHandle<CCSPlayerPawn>>(Schema.GetOffset(0x14928316EB48351F));
  }
  public ref CHandle<CCSPlayerController> PlayerControllerDamager {
    get => ref _Handle.AsRef<CHandle<CCSPlayerController>>(Schema.GetOffset(0x14928316285F9023));
  }
  public ref CHandle<CCSPlayerController> PlayerControllerRecipient {
    get => ref _Handle.AsRef<CHandle<CCSPlayerController>>(Schema.GetOffset(0x14928316033B0B25));
  }
  public string PlayerDamagerName {
    get {
      var ptr = _Handle.Read<nint>(Schema.GetOffset(0x149283165AB278AD));
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, 0x149283165AB278AD, value);
  } 
  public string PlayerRecipientName {
    get {
      var ptr = _Handle.Read<nint>(Schema.GetOffset(0x14928316E6015313));
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, 0x14928316E6015313, value);
  } 
  public ref ulong DamagerXuid {
    get => ref _Handle.AsRef<ulong>(Schema.GetOffset(0x14928316DAD4D818));
  }
  public ref ulong RecipientXuid {
    get => ref _Handle.AsRef<ulong>(Schema.GetOffset(0x1492831684A232C2));
  }
  public ref float BulletsDamage {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x149283163641E11D));
  }
  public ref float Damage {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x14928316DC60E53E));
  }
  public ref float ActualHealthRemoved {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x14928316F8DC2935));
  }
  public ref int NumHits {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0x149283162EC9980E));
  }
  public ref int LastBulletUpdate {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0x14928316D5ABC11D));
  }
  public ref bool IsOtherEnemy {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0x149283164F1F40EB));
  }
  public ref EKillTypes_t KillType {
    get => ref _Handle.AsRef<EKillTypes_t>(Schema.GetOffset(0x14928316C2ADBB11));
  }

  public void PlayerDamagerUpdated() {
    Schema.Update(_Handle, 0x149283162F5812D9);
  }
  public void PlayerRecipientUpdated() {
    Schema.Update(_Handle, 0x14928316EB48351F);
  }
  public void PlayerControllerDamagerUpdated() {
    Schema.Update(_Handle, 0x14928316285F9023);
  }
  public void PlayerControllerRecipientUpdated() {
    Schema.Update(_Handle, 0x14928316033B0B25);
  }
  public void PlayerDamagerNameUpdated() {
    Schema.Update(_Handle, 0x149283165AB278AD);
  }
  public void PlayerRecipientNameUpdated() {
    Schema.Update(_Handle, 0x14928316E6015313);
  }
  public void DamagerXuidUpdated() {
    Schema.Update(_Handle, 0x14928316DAD4D818);
  }
  public void RecipientXuidUpdated() {
    Schema.Update(_Handle, 0x1492831684A232C2);
  }
  public void DamageUpdated() {
    Schema.Update(_Handle, 0x14928316DC60E53E);
  }
  public void ActualHealthRemovedUpdated() {
    Schema.Update(_Handle, 0x14928316F8DC2935);
  }
  public void NumHitsUpdated() {
    Schema.Update(_Handle, 0x149283162EC9980E);
  }
  public void LastBulletUpdateUpdated() {
    Schema.Update(_Handle, 0x14928316D5ABC11D);
  }
  public void IsOtherEnemyUpdated() {
    Schema.Update(_Handle, 0x149283164F1F40EB);
  }
  public void KillTypeUpdated() {
    Schema.Update(_Handle, 0x14928316C2ADBB11);
  }
}