// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CDirectPlaybackTagDataImpl : SchemaClass, CDirectPlaybackTagData {

  public CDirectPlaybackTagDataImpl(nint handle) : base(handle) {
  }

  public string SequenceName {
    get {
      var ptr = _Handle.Read<nint>(Schema.GetOffset(0xAADCE162B4A24CB));
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, 0xAADCE162B4A24CB, value);
  } 
  public ref CUtlVector Tags {
    get => ref _Handle.AsRef<CUtlVector>(Schema.GetOffset(0xAADCE16B46C8540));
  }


}