// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CEntityIOOutputImpl : SchemaClass, CEntityIOOutput {

  public CEntityIOOutputImpl(nint handle) : base(handle) {
  }

  public SchemaUntypedField Value {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0xCD5B084DCB0894A));
  }


}