// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CEnvHudHintImpl : CPointEntityImpl, CEnvHudHint {

  public CEnvHudHintImpl(nint handle) : base(handle) {
  }

  public ref CUtlSymbolLarge Message {
    get => ref _Handle.AsRef<CUtlSymbolLarge>(Schema.GetOffset(0xD3D49C23CC5243DC));
  }


}