// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CEnvFadeImpl : CLogicalEntityImpl, CEnvFade {

  public CEnvFadeImpl(nint handle) : base(handle) {
  }

  public ref Color FadeColor {
    get => ref _Handle.AsRef<Color>(Schema.GetOffset(0xEFBFC063C1517BF2));
  }
  public ref float Duration {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0xEFBFC0639879A98D));
  }
  public ref float HoldDuration {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0xEFBFC0631D577A68));
  }
  public CEntityIOOutput OnBeginFade {
    get => new CEntityIOOutputImpl(_Handle + Schema.GetOffset(0xEFBFC0633308BA63));
  }

  public void FadeColorUpdated() {
    Schema.Update(_Handle, 0xEFBFC063C1517BF2);
  }
}