// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CEnvBeamImpl : CBeamImpl, CEnvBeam {

  public CEnvBeamImpl(nint handle) : base(handle) {
  }

  public ref int Active {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0x84C6714A8E29CBCF));
  }
  public ref CStrongHandle<InfoForResourceTypeIMaterial2> SpriteTexture {
    get => ref _Handle.AsRef<CStrongHandle<InfoForResourceTypeIMaterial2>>(Schema.GetOffset(0x84C6714A095DE4B7));
  }
  public string StartEntity {
    get {
      var ptr = _Handle.Read<nint>(Schema.GetOffset(0x84C6714AA162CA40));
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, 0x84C6714AA162CA40, value);
  } 
  public string EndEntity {
    get {
      var ptr = _Handle.Read<nint>(Schema.GetOffset(0x84C6714A636BA021));
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, 0x84C6714A636BA021, value);
  } 
  public ref float Life {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x84C6714AA5A4067F));
  }
  public ref float BoltWidth {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x84C6714A165169F2));
  }
  public ref float NoiseAmplitude {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x84C6714A414FFA76));
  }
  public ref int Speed {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0x84C6714AA4BD35A0));
  }
  public ref float Restrike {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x84C6714A4647E3AA));
  }
  public string SpriteName {
    get {
      var ptr = _Handle.Read<nint>(Schema.GetOffset(0x84C6714A096530FF));
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, 0x84C6714A096530FF, value);
  } 
  public ref int FrameStart {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0x84C6714ABA4C58E6));
  }
  public ref Vector EndPointWorld {
    get => ref _Handle.AsRef<Vector>(Schema.GetOffset(0x84C6714ADCC233A4));
  }
  public ref Vector EndPointRelative {
    get => ref _Handle.AsRef<Vector>(Schema.GetOffset(0x84C6714AA25C0E48));
  }
  public ref float Radius {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x84C6714AA921CA53));
  }
  public ref Touch_t TouchType {
    get => ref _Handle.AsRef<Touch_t>(Schema.GetOffset(0x84C6714A159DBEB0));
  }
  public string FilterName {
    get {
      var ptr = _Handle.Read<nint>(Schema.GetOffset(0x84C6714A09C86445));
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, 0x84C6714A09C86445, value);
  } 
  public ref CHandle<CBaseEntity> Filter {
    get => ref _Handle.AsRef<CHandle<CBaseEntity>>(Schema.GetOffset(0x84C6714A45D9E0B1));
  }
  public string Decal {
    get {
      var ptr = _Handle.Read<nint>(Schema.GetOffset(0x84C6714AC8536FA6));
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, 0x84C6714AC8536FA6, value);
  } 
  public CEntityIOOutput OnTouchedByEntity {
    get => new CEntityIOOutputImpl(_Handle + Schema.GetOffset(0x84C6714ACB930C48));
  }


}