// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CFilterModelImpl : CBaseFilterImpl, CFilterModel {

  public CFilterModelImpl(nint handle) : base(handle) {
  }

  public string FilterModel {
    get {
      var ptr = _Handle.Read<nint>(Schema.GetOffset(0x59DA03B921E36753));
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, 0x59DA03B921E36753, value);
  } 


}