// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CFilterMassGreaterImpl : CBaseFilterImpl, CFilterMassGreater {

  public CFilterMassGreaterImpl(nint handle) : base(handle) {
  }

  public ref float FilterMass {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0xBF74FA22FF3F08E7));
  }


}