// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CFlashbangProjectileImpl : CBaseCSGrenadeProjectileImpl, CFlashbangProjectile {

  public CFlashbangProjectileImpl(nint handle) : base(handle) {
  }

  public ref float TimeToDetonate {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x9F4F2EA190E2E597));
  }
  public ref byte NumOpponentsHit {
    get => ref _Handle.AsRef<byte>(Schema.GetOffset(0x9F4F2EA1CA7913A4));
  }
  public ref byte NumTeammatesHit {
    get => ref _Handle.AsRef<byte>(Schema.GetOffset(0x9F4F2EA1BC5B8F41));
  }


}