// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CFlexControllerImpl : SchemaClass, CFlexController {

  public CFlexControllerImpl(nint handle) : base(handle) {
  }

  public string Name {
    get {
      var ptr = _Handle.Read<nint>(Schema.GetOffset(0x5265FDF16750BACB));
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, 0x5265FDF16750BACB, value);
  } 
  public string Type {
    get {
      var ptr = _Handle.Read<nint>(Schema.GetOffset(0x5265FDF1B580AB00));
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, 0x5265FDF1B580AB00, value);
  } 
  public ref float Min {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x5265FDF1C98F4557));
  }
  public ref float Max {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x5265FDF1D7A2E319));
  }


}