// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CFootCycleMetricEvaluatorImpl : CMotionMetricEvaluatorImpl, CFootCycleMetricEvaluator {

  public CFootCycleMetricEvaluatorImpl(nint handle) : base(handle) {
  }

  public ref CUtlVector<int> FootIndices {
    get => ref _Handle.AsRef<CUtlVector<int>>(Schema.GetOffset(0x1773C1814C840316));
  }


}