// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CFootFallAnimTagImpl : CAnimTagBaseImpl, CFootFallAnimTag {

  public CFootFallAnimTagImpl(nint handle) : base(handle) {
  }

  public ref FootFallTagFoot_t Foot {
    get => ref _Handle.AsRef<FootFallTagFoot_t>(Schema.GetOffset(0xC142B61EEB2B8B39));
  }


}