// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CFootStepTriggerUpdateNodeImpl : CUnaryUpdateNodeImpl, CFootStepTriggerUpdateNode {

  public CFootStepTriggerUpdateNodeImpl(nint handle) : base(handle) {
  }

  public ref CUtlVector Triggers {
    get => ref _Handle.AsRef<CUtlVector>(Schema.GetOffset(0x799A3B55684C6AF0));
  }
  public ref float Tolerance {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x799A3B558C29728E));
  }


}