// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CFuseSymbolTableImpl : SchemaClass, CFuseSymbolTable {

  public CFuseSymbolTableImpl(nint handle) : base(handle) {
  }

  public ref CUtlVector Constants {
    get => ref _Handle.AsRef<CUtlVector>(Schema.GetOffset(0xD8A03B41460C1382));
  }
  public ref CUtlVector Variables {
    get => ref _Handle.AsRef<CUtlVector>(Schema.GetOffset(0xD8A03B4106AE7DE2));
  }
  public ref CUtlVector Functions {
    get => ref _Handle.AsRef<CUtlVector>(Schema.GetOffset(0xD8A03B41F6EF246E));
  }
  public SchemaUntypedField ConstantMap {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0xD8A03B4198BF6E51));
  }
  public SchemaUntypedField VariableMap {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0xD8A03B410FDE3671));
  }
  public SchemaUntypedField FunctionMap {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0xD8A03B4147A33EC5));
  }


}