// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CHitBoxSetImpl : SchemaClass, CHitBoxSet {

  public CHitBoxSetImpl(nint handle) : base(handle) {
  }

  public ref CUtlString Name {
    get => ref _Handle.AsRef<CUtlString>(Schema.GetOffset(0x742AE9EC4D8F5786));
  }
  public ref uint NameHash {
    get => ref _Handle.AsRef<uint>(Schema.GetOffset(0x742AE9ECDE15EEFE));
  }
  public ref CUtlVector HitBoxes {
    get => ref _Handle.AsRef<CUtlVector>(Schema.GetOffset(0x742AE9EC07A4113F));
  }
  public ref CUtlString SourceFilename {
    get => ref _Handle.AsRef<CUtlString>(Schema.GetOffset(0x742AE9ECD49CE26D));
  }


}