// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CLogicDistanceCheckImpl : CLogicalEntityImpl, CLogicDistanceCheck {

  public CLogicDistanceCheckImpl(nint handle) : base(handle) {
  }

  public string EntityA {
    get {
      var ptr = _Handle.Read<nint>(Schema.GetOffset(0x523E7E6D07823CB9));
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, 0x523E7E6D07823CB9, value);
  } 
  public string EntityB {
    get {
      var ptr = _Handle.Read<nint>(Schema.GetOffset(0x523E7E6D04823800));
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, 0x523E7E6D04823800, value);
  } 
  public ref float Zone1Distance {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x523E7E6DFF385A8F));
  }
  public ref float Zone2Distance {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x523E7E6DE1734A1A));
  }
  public CEntityIOOutput InZone1 {
    get => new CEntityIOOutputImpl(_Handle + Schema.GetOffset(0x523E7E6D25378DB3));
  }
  public CEntityIOOutput InZone2 {
    get => new CEntityIOOutputImpl(_Handle + Schema.GetOffset(0x523E7E6D26378F46));
  }
  public CEntityIOOutput InZone3 {
    get => new CEntityIOOutputImpl(_Handle + Schema.GetOffset(0x523E7E6D273790D9));
  }


}