// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CLogicGameEventListenerImpl : CLogicalEntityImpl, CLogicGameEventListener {

  public CLogicGameEventListenerImpl(nint handle) : base(handle) {
  }

  public CEntityIOOutput OnEventFired {
    get => new CEntityIOOutputImpl(_Handle + Schema.GetOffset(0xB18EF22E84EA158));
  }
  public string GameEventName {
    get {
      var ptr = _Handle.Read<nint>(Schema.GetOffset(0xB18EF22C6581BAE));
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, 0xB18EF22C6581BAE, value);
  } 
  public string GameEventItem {
    get {
      var ptr = _Handle.Read<nint>(Schema.GetOffset(0xB18EF22ACB669EE));
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, 0xB18EF22ACB669EE, value);
  } 
  public ref bool Enabled {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0xB18EF226154EB7E));
  }
  public ref bool StartDisabled {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0xB18EF2261ED0C4F));
  }

  public void EnabledUpdated() {
    Schema.Update(_Handle, 0xB18EF226154EB7E);
  }
}