// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CMomentaryRotButtonImpl : CRotButtonImpl, CMomentaryRotButton {

  public CMomentaryRotButtonImpl(nint handle) : base(handle) {
  }

  public SchemaUntypedField Position {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0x85A553CDFC27FA8A));
  }
  public CEntityIOOutput OnUnpressed {
    get => new CEntityIOOutputImpl(_Handle + Schema.GetOffset(0x85A553CD446980EB));
  }
  public CEntityIOOutput OnFullyOpen {
    get => new CEntityIOOutputImpl(_Handle + Schema.GetOffset(0x85A553CD21733AE4));
  }
  public CEntityIOOutput OnFullyClosed {
    get => new CEntityIOOutputImpl(_Handle + Schema.GetOffset(0x85A553CD75470294));
  }
  public CEntityIOOutput OnReachedPosition {
    get => new CEntityIOOutputImpl(_Handle + Schema.GetOffset(0x85A553CDC5B3EAA5));
  }
  public ref int LastUsed {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0x85A553CD3297229C));
  }
  public ref QAngle Start {
    get => ref _Handle.AsRef<QAngle>(Schema.GetOffset(0x85A553CDA539BEFF));
  }
  public ref QAngle End {
    get => ref _Handle.AsRef<QAngle>(Schema.GetOffset(0x85A553CD5B29CFCA));
  }
  public ref float IdealYaw {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x85A553CD48C477F5));
  }
  public ref CUtlSymbolLarge Noise {
    get => ref _Handle.AsRef<CUtlSymbolLarge>(Schema.GetOffset(0x85A553CD1F22B8CC));
  }
  public ref bool UpdateTarget {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0x85A553CDBE14BF5D));
  }
  public ref int Direction {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0x85A553CDEF16898A));
  }
  public ref float ReturnSpeed {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x85A553CDDFA1CF5A));
  }
  public ref float StartPosition {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x85A553CDE34367EA));
  }


}