// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CMorphRectDataImpl : SchemaClass, CMorphRectData {

  public CMorphRectDataImpl(nint handle) : base(handle) {
  }

  public ref short XLeftDst {
    get => ref _Handle.AsRef<short>(Schema.GetOffset(0xB12257C224FC92D5));
  }
  public ref short YTopDst {
    get => ref _Handle.AsRef<short>(Schema.GetOffset(0xB12257C291EBF0D2));
  }
  public ref float UWidthSrc {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0xB12257C29F37ECB8));
  }
  public ref float VHeightSrc {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0xB12257C230C84BA2));
  }
  public ref CUtlVector<CMorphBundleData> BundleDatas {
    get => ref _Handle.AsRef<CUtlVector<CMorphBundleData>>(Schema.GetOffset(0xB12257C255A3B6A2));
  }


}