// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CMultiplayer_ExpresserImpl : CAI_ExpresserWithFollowupImpl, CMultiplayer_Expresser {

  public CMultiplayer_ExpresserImpl(nint handle) : base(handle) {
  }

  public ref bool AllowMultipleScenes {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0x19772F22AE5FCD97));
  }


}