// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CMultiLightProxyImpl : CLogicalEntityImpl, CMultiLightProxy {

  public CMultiLightProxyImpl(nint handle) : base(handle) {
  }

  public ref CUtlSymbolLarge LightNameFilter {
    get => ref _Handle.AsRef<CUtlSymbolLarge>(Schema.GetOffset(0xF2B647B3071F3A26));
  }
  public ref CUtlSymbolLarge LightClassFilter {
    get => ref _Handle.AsRef<CUtlSymbolLarge>(Schema.GetOffset(0xF2B647B32B566D5B));
  }
  public ref float LightRadiusFilter {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0xF2B647B3DBC59891));
  }
  public ref float BrightnessDelta {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0xF2B647B3E60D5182));
  }
  public ref bool PerformScreenFade {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0xF2B647B3F3DAE928));
  }
  public ref float TargetBrightnessMultiplier {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0xF2B647B3B84CF4BA));
  }
  public ref float CurrentBrightnessMultiplier {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0xF2B647B3C03C5EEC));
  }
  public ref CUtlVector<CHandle<CLightEntity>> Lights {
    get => ref _Handle.AsRef<CUtlVector<CHandle<CLightEntity>>>(Schema.GetOffset(0xF2B647B3A5ECA534));
  }


}