// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNetworkViewOffsetVectorImpl : SchemaClass, CNetworkViewOffsetVector {

  public CNetworkViewOffsetVectorImpl(nint handle) : base(handle) {
  }

  public ref CNetworkedQuantizedFloat X {
    get => ref _Handle.AsRef<CNetworkedQuantizedFloat>(Schema.GetOffset(0x178DD1B58FEB7867));
  }
  public ref CNetworkedQuantizedFloat Y {
    get => ref _Handle.AsRef<CNetworkedQuantizedFloat>(Schema.GetOffset(0x178DD1B58EEB76D4));
  }
  public ref CNetworkedQuantizedFloat Z {
    get => ref _Handle.AsRef<CNetworkedQuantizedFloat>(Schema.GetOffset(0x178DD1B591EB7B8D));
  }

  public void XUpdated() {
    Schema.Update(_Handle, 0x178DD1B58FEB7867);
  }
  public void YUpdated() {
    Schema.Update(_Handle, 0x178DD1B58EEB76D4);
  }
  public void ZUpdated() {
    Schema.Update(_Handle, 0x178DD1B591EB7B8D);
  }
}