// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmAimCSNode__CDefinitionImpl : CNmPassthroughNode__CDefinitionImpl, CNmAimCSNode__CDefinition {

  public CNmAimCSNode__CDefinitionImpl(nint handle) : base(handle) {
  }

  public ref short VerticalAngleNodeIdx {
    get => ref _Handle.AsRef<short>(Schema.GetOffset(0xE1CD14C20A1F17AD));
  }
  public ref short HorizontalAngleNodeIdx {
    get => ref _Handle.AsRef<short>(Schema.GetOffset(0xE1CD14C28E2FD3DB));
  }
  public ref short EnabledNodeIdx {
    get => ref _Handle.AsRef<short>(Schema.GetOffset(0xE1CD14C2F7CDF5E9));
  }
  public ref float BlendTimeSeconds {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0xE1CD14C26D3A08FC));
  }


}