// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmAndNode__CDefinitionImpl : CNmBoolValueNode__CDefinitionImpl, CNmAndNode__CDefinition {

  public CNmAndNode__CDefinitionImpl(nint handle) : base(handle) {
  }

  public SchemaUntypedField ConditionNodeIndices {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0xC46B12E04A144D0F));
  }


}