// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmBoneMaskNode__CDefinitionImpl : CNmBoneMaskValueNode__CDefinitionImpl, CNmBoneMaskNode__CDefinition {

  public CNmBoneMaskNode__CDefinitionImpl(nint handle) : base(handle) {
  }

  public ref CGlobalSymbol BoneMaskID {
    get => ref _Handle.AsRef<CGlobalSymbol>(Schema.GetOffset(0xC50CAD4B5F09FD66));
  }


}