// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmFloatCurveEventImpl : CNmEventImpl, CNmFloatCurveEvent {

  public CNmFloatCurveEventImpl(nint handle) : base(handle) {
  }

  public ref CGlobalSymbol ID {
    get => ref _Handle.AsRef<CGlobalSymbol>(Schema.GetOffset(0x79BEBEA95066900));
  }
  public SchemaUntypedField Curve {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0x79BEBEABFFA0B34));
  }


}