// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmIsTargetSetNode__CDefinitionImpl : CNmBoolValueNode__CDefinitionImpl, CNmIsTargetSetNode__CDefinition {

  public CNmIsTargetSetNode__CDefinitionImpl(nint handle) : base(handle) {
  }

  public ref short InputValueNodeIdx {
    get => ref _Handle.AsRef<short>(Schema.GetOffset(0x27C85C3E95E89F27));
  }


}