// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmStateNode__CDefinitionImpl : CNmPoseNode__CDefinitionImpl, CNmStateNode__CDefinition {

  public CNmStateNode__CDefinitionImpl(nint handle) : base(handle) {
  }

  public ref short ChildNodeIdx {
    get => ref _Handle.AsRef<short>(Schema.GetOffset(0x1C1728105C29A73C));
  }
  public SchemaUntypedField EntryEvents {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0x1C172810211A7856));
  }
  public SchemaUntypedField ExecuteEvents {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0x1C1728103BF4FF69));
  }
  public SchemaUntypedField ExitEvents {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0x1C17281096F711C4));
  }
  public SchemaUntypedField TimedRemainingEvents {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0x1C172810DFC9D945));
  }
  public SchemaUntypedField TimedElapsedEvents {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0x1C172810E054F8B9));
  }
  public ref short LayerWeightNodeIdx {
    get => ref _Handle.AsRef<short>(Schema.GetOffset(0x1C17281069611331));
  }
  public ref short LayerRootMotionWeightNodeIdx {
    get => ref _Handle.AsRef<short>(Schema.GetOffset(0x1C17281040566E47));
  }
  public ref short LayerBoneMaskNodeIdx {
    get => ref _Handle.AsRef<short>(Schema.GetOffset(0x1C1728101BA67627));
  }
  public ref bool IsOffState {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0x1C172810291F238F));
  }


}