// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmSyncEventIndexConditionNode__CDefinitionImpl : CNmBoolValueNode__CDefinitionImpl, CNmSyncEventIndexConditionNode__CDefinition {

  public CNmSyncEventIndexConditionNode__CDefinitionImpl(nint handle) : base(handle) {
  }

  public ref short SourceStateNodeIdx {
    get => ref _Handle.AsRef<short>(Schema.GetOffset(0x343CD5DB63F0228C));
  }
  public ref CNmSyncEventIndexConditionNode__TriggerMode_t TriggerMode {
    get => ref _Handle.AsRef<CNmSyncEventIndexConditionNode__TriggerMode_t>(Schema.GetOffset(0x343CD5DB0431A60C));
  }
  public ref int SyncEventIdx {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0x343CD5DBC84F66C9));
  }


}