// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CParticleFunctionRendererImpl : CParticleFunctionImpl, CParticleFunctionRenderer {

  public CParticleFunctionRendererImpl(nint handle) : base(handle) {
  }

  public CParticleVisibilityInputs VisibilityInputs {
    get => new CParticleVisibilityInputsImpl(_Handle + Schema.GetOffset(0xAE332DA3CF8264F8));
  }
  public ref bool CannotBeRefracted {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0xAE332DA3CC78C4FB));
  }
  public ref bool SkipRenderingOnMobile {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0xAE332DA33F34EA75));
  }


}