// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CParamSpanUpdaterImpl : SchemaClass, CParamSpanUpdater {

  public CParamSpanUpdaterImpl(nint handle) : base(handle) {
  }

  public ref CUtlVector<ParamSpan_t> Spans {
    get => ref _Handle.AsRef<CUtlVector<ParamSpan_t>>(Schema.GetOffset(0xA35886AC66213056));
  }


}