// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPhysSurfacePropertiesSoundNamesImpl : SchemaClass, CPhysSurfacePropertiesSoundNames {

  public CPhysSurfacePropertiesSoundNamesImpl(nint handle) : base(handle) {
  }

  public ref CUtlString ImpactSoft {
    get => ref _Handle.AsRef<CUtlString>(Schema.GetOffset(0xF2658A3949E7237B));
  }
  public ref CUtlString ImpactHard {
    get => ref _Handle.AsRef<CUtlString>(Schema.GetOffset(0xF2658A3934A77BB2));
  }
  public ref CUtlString ScrapeSmooth {
    get => ref _Handle.AsRef<CUtlString>(Schema.GetOffset(0xF2658A3902EA935F));
  }
  public ref CUtlString ScrapeRough {
    get => ref _Handle.AsRef<CUtlString>(Schema.GetOffset(0xF2658A39CE764A7E));
  }
  public ref CUtlString BulletImpact {
    get => ref _Handle.AsRef<CUtlString>(Schema.GetOffset(0xF2658A3943E056BB));
  }
  public ref CUtlString Rolling {
    get => ref _Handle.AsRef<CUtlString>(Schema.GetOffset(0xF2658A39E0171912));
  }
  public ref CUtlString Break {
    get => ref _Handle.AsRef<CUtlString>(Schema.GetOffset(0xF2658A39382B2298));
  }
  public ref CUtlString Strain {
    get => ref _Handle.AsRef<CUtlString>(Schema.GetOffset(0xF2658A397EDA2E10));
  }
  public ref CUtlString MeleeImpact {
    get => ref _Handle.AsRef<CUtlString>(Schema.GetOffset(0xF2658A3976A52491));
  }
  public ref CUtlString PushOff {
    get => ref _Handle.AsRef<CUtlString>(Schema.GetOffset(0xF2658A39C825B1A2));
  }
  public ref CUtlString SkidStop {
    get => ref _Handle.AsRef<CUtlString>(Schema.GetOffset(0xF2658A3976C778AE));
  }
  public ref CUtlString Resonant {
    get => ref _Handle.AsRef<CUtlString>(Schema.GetOffset(0xF2658A396BA8FAF5));
  }


}