// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPhysSurfacePropertiesVehicleImpl : SchemaClass, CPhysSurfacePropertiesVehicle {

  public CPhysSurfacePropertiesVehicleImpl(nint handle) : base(handle) {
  }

  public ref float WheelDrag {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x5B1104DCC04986AE));
  }
  public ref float WheelFrictionScale {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x5B1104DC7A6D9A4C));
  }


}