// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPlatTriggerImpl : CBaseModelEntityImpl, CPlatTrigger {

  public CPlatTriggerImpl(nint handle) : base(handle) {
  }

  public ref CHandle<CFuncPlat> Platform {
    get => ref _Handle.AsRef<CHandle<CFuncPlat>>(Schema.GetOffset(0xE5D76A656D16AFF0));
  }


}