// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPlayerInputAnimMotorUpdaterImpl : CAnimMotorUpdaterBaseImpl, CPlayerInputAnimMotorUpdater {

  public CPlayerInputAnimMotorUpdaterImpl(nint handle) : base(handle) {
  }

  public ref CUtlVector<float> SampleTimes {
    get => ref _Handle.AsRef<CUtlVector<float>>(Schema.GetOffset(0xA117CC02471975DF));
  }
  public ref float SpringConstant {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0xA117CC02CE2260BE));
  }
  public ref float AnticipationDistance {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0xA117CC0264273401));
  }
  public CAnimParamHandle AnticipationPosParam {
    get => new CAnimParamHandleImpl(_Handle + Schema.GetOffset(0xA117CC0286389829));
  }
  public CAnimParamHandle AnticipationHeadingParam {
    get => new CAnimParamHandleImpl(_Handle + Schema.GetOffset(0xA117CC02095DAB6D));
  }
  public ref bool UseAcceleration {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0xA117CC02254F8B08));
  }


}