// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CProductQuantizerImpl : SchemaClass, CProductQuantizer {

  public CProductQuantizerImpl(nint handle) : base(handle) {
  }

  public ref CUtlVector<CVectorQuantizer> SubQuantizers {
    get => ref _Handle.AsRef<CUtlVector<CVectorQuantizer>>(Schema.GetOffset(0x5B1A8128593CF0B5));
  }
  public ref int Dimensions {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0x5B1A81282D8795AC));
  }


}