// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPulseCell_Inflow_MethodImpl : CPulseCell_Inflow_BaseEntrypointImpl, CPulseCell_Inflow_Method {

  public CPulseCell_Inflow_MethodImpl(nint handle) : base(handle) {
  }

  public SchemaUntypedField MethodName {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0xFB5926557D863B13));
  }
  public string Description {
    get {
      var ptr = _Handle.Read<nint>(Schema.GetOffset(0xFB592655678744E9));
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, 0xFB592655678744E9, value);
  } 
  public ref bool IsPublic {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0xFB592655BAE30B50));
  }
  public SchemaUntypedField ReturnType {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0xFB59265566333D67));
  }
  public ref CUtlLeanVector<CPulseRuntimeMethodArg, int> Args {
    get => ref _Handle.AsRef<CUtlLeanVector<CPulseRuntimeMethodArg, int>>(Schema.GetOffset(0xFB592655DAB98BBC));
  }


}