// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPulseCell_Inflow_EventHandlerImpl : CPulseCell_Inflow_BaseEntrypointImpl, CPulseCell_Inflow_EventHandler {

  public CPulseCell_Inflow_EventHandlerImpl(nint handle) : base(handle) {
  }

  public SchemaUntypedField EventName {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0x9BAF9AD81DFEB13C));
  }


}