// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPulseCell_PlaySequenceImpl : CPulseCell_BaseYieldingInflowImpl, CPulseCell_PlaySequence {

  public CPulseCell_PlaySequenceImpl(nint handle) : base(handle) {
  }

  public ref CUtlString SequenceName {
    get => ref _Handle.AsRef<CUtlString>(Schema.GetOffset(0xE313765BA270F66B));
  }
  public PulseNodeDynamicOutflows_t PulseAnimEvents {
    get => new PulseNodeDynamicOutflows_tImpl(_Handle + Schema.GetOffset(0xE313765B10F0A082));
  }
  public CPulse_ResumePoint OnFinished {
    get => new CPulse_ResumePointImpl(_Handle + Schema.GetOffset(0xE313765B8D903E5E));
  }
  public CPulse_ResumePoint OnCanceled {
    get => new CPulse_ResumePointImpl(_Handle + Schema.GetOffset(0xE313765BF02162DB));
  }


}