// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPulseCell_FireCursorsImpl : CPulseCell_BaseYieldingInflowImpl, CPulseCell_FireCursors {

  public CPulseCell_FireCursorsImpl(nint handle) : base(handle) {
  }

  public ref CUtlVector<CPulse_OutflowConnection> Outflows {
    get => ref _Handle.AsRef<CUtlVector<CPulse_OutflowConnection>>(Schema.GetOffset(0x9BFA034F8F0AFDF8));
  }
  public ref bool WaitForChildOutflows {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0x9BFA034F3F8E29C6));
  }
  public CPulse_ResumePoint OnFinished {
    get => new CPulse_ResumePointImpl(_Handle + Schema.GetOffset(0x9BFA034F8D903E5E));
  }
  public CPulse_ResumePoint OnCanceled {
    get => new CPulse_ResumePointImpl(_Handle + Schema.GetOffset(0x9BFA034FF02162DB));
  }


}