// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPulseCell_Outflow_ListenForEntityOutputImpl : CPulseCell_BaseYieldingInflowImpl, CPulseCell_Outflow_ListenForEntityOutput {

  public CPulseCell_Outflow_ListenForEntityOutputImpl(nint handle) : base(handle) {
  }

  public SignatureOutflow_Resume OnFired {
    get => new SignatureOutflow_ResumeImpl(_Handle + Schema.GetOffset(0xCB35163784825730));
  }
  public CPulse_ResumePoint OnCanceled {
    get => new CPulse_ResumePointImpl(_Handle + Schema.GetOffset(0xCB351637F02162DB));
  }
  public ref CGlobalSymbol StrEntityOutput {
    get => ref _Handle.AsRef<CGlobalSymbol>(Schema.GetOffset(0xCB351637C8E70456));
  }
  public string StrEntityOutputParam {
    get {
      var ptr = _Handle.Read<nint>(Schema.GetOffset(0xCB351637BB356637));
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, 0xCB351637BB356637, value);
  } 
  public ref bool ListenUntilCanceled {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0xCB351637C798285D));
  }


}