// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPulse_ChunkImpl : SchemaClass, CPulse_Chunk {

  public CPulse_ChunkImpl(nint handle) : base(handle) {
  }

  public ref CUtlLeanVector<PGDInstruction_t, int> Instructions {
    get => ref _Handle.AsRef<CUtlLeanVector<PGDInstruction_t, int>>(Schema.GetOffset(0x816932094D358BC4));
  }
  public ref CUtlLeanVector<CPulse_RegisterInfo, int> Registers {
    get => ref _Handle.AsRef<CUtlLeanVector<CPulse_RegisterInfo, int>>(Schema.GetOffset(0x81693209BB828A49));
  }
  public ref CUtlLeanVector<PulseDocNodeID_t, int> InstructionEditorIDs {
    get => ref _Handle.AsRef<CUtlLeanVector<PulseDocNodeID_t, int>>(Schema.GetOffset(0x81693209236D8B64));
  }


}