// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPulseGraphInstance_TestDomain_DerivedImpl : CPulseGraphInstance_TestDomainImpl, CPulseGraphInstance_TestDomain_Derived {

  public CPulseGraphInstance_TestDomain_DerivedImpl(nint handle) : base(handle) {
  }

  public ref int InstanceValueX {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0x439D00CDD2DC0135));
  }


}