// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPulseCell_Value_RandomIntImpl : CPulseCell_BaseValueImpl, CPulseCell_Value_RandomInt {

  public CPulseCell_Value_RandomIntImpl(nint handle) : base(handle) {
  }




}