// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPulse_OutputConnectionImpl : SchemaClass, CPulse_OutputConnection {

  public CPulse_OutputConnectionImpl(nint handle) : base(handle) {
  }

  public SchemaUntypedField SourceOutput {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0x6DEBCD452D46D7F5));
  }
  public SchemaUntypedField TargetEntity {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0x6DEBCD45948B1533));
  }
  public SchemaUntypedField TargetInput {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0x6DEBCD45F1A0003C));
  }
  public SchemaUntypedField Param {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0x6DEBCD45E85FEBB2));
  }


}