// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CRotatorTargetImpl : CPointEntityImpl, CRotatorTarget {

  public CRotatorTargetImpl(nint handle) : base(handle) {
  }

  public CEntityIOOutput OnArrivedAt {
    get => new CEntityIOOutputImpl(_Handle + Schema.GetOffset(0x448D6B2611C20554));
  }
  public ref RotatorTargetSpace_t Space {
    get => ref _Handle.AsRef<RotatorTargetSpace_t>(Schema.GetOffset(0x448D6B26A8FD0676));
  }


}