// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CScriptUniformRandomStreamImpl : SchemaClass, CScriptUniformRandomStream {

  public CScriptUniformRandomStreamImpl(nint handle) : base(handle) {
  }

  public SchemaUntypedField ScriptScope {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0xF6699588B14F90D4));
  }
  public ref int InitialSeed {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0xF6699588944D5EB2));
  }


}