// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CSlowDownOnSlopesUpdateNodeImpl : CUnaryUpdateNodeImpl, CSlowDownOnSlopesUpdateNode {

  public CSlowDownOnSlopesUpdateNodeImpl(nint handle) : base(handle) {
  }

  public ref float SlowDownStrength {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x196FB4938D85E247));
  }


}