// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CSosSoundEventGroupSchemaImpl : SchemaClass, CSosSoundEventGroupSchema {

  public CSosSoundEventGroupSchemaImpl(nint handle) : base(handle) {
  }

  public ref CUtlString Name {
    get => ref _Handle.AsRef<CUtlString>(Schema.GetOffset(0x25BA87004D8F5786));
  }
  public ref SosGroupType_t Type {
    get => ref _Handle.AsRef<SosGroupType_t>(Schema.GetOffset(0x25BA870018853D59));
  }
  public ref bool IsBlocking {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0x25BA87001C9AB88E));
  }
  public ref int BlockMaxCount {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0x25BA8700282E91F7));
  }
  public ref bool InvertMatch {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0x25BA87003C3CF99A));
  }
  public CSosGroupMatchPattern MatchPattern {
    get => new CSosGroupMatchPatternImpl(_Handle + Schema.GetOffset(0x25BA8700E065AB84));
  }
  public CSosGroupBranchPattern BranchPattern {
    get => new CSosGroupBranchPatternImpl(_Handle + Schema.GetOffset(0x25BA870017E92C29));
  }
  public ref float LifeSpanTime {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x25BA870068189B78));
  }
  public SchemaUntypedField Actions {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0x25BA8700D36B7908));
  }


}