// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CSosGroupActionSchemaImpl : SchemaClass, CSosGroupActionSchema {

  public CSosGroupActionSchemaImpl(nint handle) : base(handle) {
  }

  public ref CUtlString Name {
    get => ref _Handle.AsRef<CUtlString>(Schema.GetOffset(0x771FE4F94D8F5786));
  }
  public ref ActionType_t ActionType {
    get => ref _Handle.AsRef<ActionType_t>(Schema.GetOffset(0x771FE4F9EF21DE07));
  }
  public ref ActionType_t ActionInstanceType {
    get => ref _Handle.AsRef<ActionType_t>(Schema.GetOffset(0x771FE4F936EAD9F4));
  }


}