// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CSosGroupActionSetSoundeventParameterSchemaImpl : CSosGroupActionSchemaImpl, CSosGroupActionSetSoundeventParameterSchema {

  public CSosGroupActionSetSoundeventParameterSchemaImpl(nint handle) : base(handle) {
  }

  public ref int MaxCount {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0x40D29D8964BED864));
  }
  public ref float MinValue {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x40D29D897C31AC56));
  }
  public ref float MaxValue {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x40D29D89D0A5C87C));
  }
  public string OpvarName {
    get {
      var ptr = _Handle.Read<nint>(Schema.GetOffset(0x40D29D894ECBF7E4));
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, 0x40D29D894ECBF7E4, value);
  } 
  public ref SosActionSortType_t SortType {
    get => ref _Handle.AsRef<SosActionSortType_t>(Schema.GetOffset(0x40D29D892E0E44B5));
  }


}