// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CSoundStackSaveImpl : CLogicalEntityImpl, CSoundStackSave {

  public CSoundStackSaveImpl(nint handle) : base(handle) {
  }

  public ref CUtlSymbolLarge StackName {
    get => ref _Handle.AsRef<CUtlSymbolLarge>(Schema.GetOffset(0xF9E7A22E3B3E9CD4));
  }


}