// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CSoundEventParameterImpl : CBaseEntityImpl, CSoundEventParameter {

  public CSoundEventParameterImpl(nint handle) : base(handle) {
  }

  public string ParamName {
    get {
      var ptr = _Handle.Read<nint>(Schema.GetOffset(0xEFEED49AFF6F4311));
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, 0xEFEED49AFF6F4311, value);
  } 
  public ref float FloatValue {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0xEFEED49A80BDA558));
  }


}