// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CSoundPatchImpl : SchemaClass, CSoundPatch {

  public CSoundPatchImpl(nint handle) : base(handle) {
  }

  public CSoundEnvelope Pitch {
    get => new CSoundEnvelopeImpl(_Handle + Schema.GetOffset(0xBE66ED3D12AC36D1));
  }
  public CSoundEnvelope Volume {
    get => new CSoundEnvelopeImpl(_Handle + Schema.GetOffset(0xBE66ED3DE3962F2F));
  }
  public ref float ShutdownTime {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0xBE66ED3DFA135362));
  }
  public ref float LastTime {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0xBE66ED3D2E79549E));
  }
  public string SoundScriptName {
    get {
      var ptr = _Handle.Read<nint>(Schema.GetOffset(0xBE66ED3D6486B844));
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, 0xBE66ED3D6486B844, value);
  } 
  public ref CHandle<CBaseEntity> Ent {
    get => ref _Handle.AsRef<CHandle<CBaseEntity>>(Schema.GetOffset(0xBE66ED3D8BBDB334));
  }
  public ref uint SoundEntityIndex {
    get => ref _Handle.AsRef<uint>(Schema.GetOffset(0xBE66ED3DEC098195));
  }
  public ref Vector SoundOrigin {
    get => ref _Handle.AsRef<Vector>(Schema.GetOffset(0xBE66ED3D384D083E));
  }
  public ref int IsPlaying {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0xBE66ED3D71CADDE5));
  }
  public CCopyRecipientFilter Filter {
    get => new CCopyRecipientFilterImpl(_Handle + Schema.GetOffset(0xBE66ED3D368220F7));
  }
  public ref float CloseCaptionDuration {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0xBE66ED3D71B7507D));
  }
  public ref bool UpdatedSoundOrigin {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0xBE66ED3DACCF22F1));
  }
  public string ClassName {
    get {
      var ptr = _Handle.Read<nint>(Schema.GetOffset(0xBE66ED3D71BB2314));
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, 0xBE66ED3D71BB2314, value);
  } 


}