// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CSpeedScaleUpdateNodeImpl : CUnaryUpdateNodeImpl, CSpeedScaleUpdateNode {

  public CSpeedScaleUpdateNodeImpl(nint handle) : base(handle) {
  }

  public CAnimParamHandle ParamIndex {
    get => new CAnimParamHandleImpl(_Handle + Schema.GetOffset(0xD43012BC61990A86));
  }


}