// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CSSDSMsg_ViewTargetImpl : SchemaClass, CSSDSMsg_ViewTarget {

  public CSSDSMsg_ViewTargetImpl(nint handle) : base(handle) {
  }

  public string Name {
    get {
      var ptr = _Handle.Read<nint>(Schema.GetOffset(0x4F31099BCAE8A266));
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, 0x4F31099BCAE8A266, value);
  } 
  public ref ulong TextureId {
    get => ref _Handle.AsRef<ulong>(Schema.GetOffset(0x4F31099B67AB25D9));
  }
  public ref int Width {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0x4F31099B119108BB));
  }
  public ref int Height {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0x4F31099BCAB61C56));
  }
  public ref int RequestedWidth {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0x4F31099BCCA175E9));
  }
  public ref int RequestedHeight {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0x4F31099B145278D8));
  }
  public ref int NumMipLevels {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0x4F31099BD64413AC));
  }
  public ref int Depth {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0x4F31099BB725DB96));
  }
  public ref int MultisampleNumSamples {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0x4F31099B1B468317));
  }
  public ref int Format {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0x4F31099BA87491AE));
  }


}