// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CStateNodeTransitionDataImpl : SchemaClass, CStateNodeTransitionData {

  public CStateNodeTransitionDataImpl(nint handle) : base(handle) {
  }

  public CBlendCurve Curve {
    get => new CBlendCurveImpl(_Handle + Schema.GetOffset(0xFC9FD460BFFA0B34));
  }
  public SchemaUntypedField BlendDuration {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0xFC9FD460BC9B1228));
  }
  public SchemaUntypedField ResetCycleValue {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0xFC9FD4609897AC3F));
  }
  public SchemaUntypedField Reset {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0xFC9FD460F99F9AA0));
  }
  public SchemaUntypedField ResetCycleOption {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0xFC9FD460A597A1E3));
  }


}