// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CStateUpdateDataImpl : SchemaClass, CStateUpdateData {

  public CStateUpdateDataImpl(nint handle) : base(handle) {
  }

  public string Name {
    get {
      var ptr = _Handle.Read<nint>(Schema.GetOffset(0xD984C8C64D8F5786));
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, 0xD984C8C64D8F5786, value);
  } 
  public AnimScriptHandle Script {
    get => new AnimScriptHandleImpl(_Handle + Schema.GetOffset(0xD984C8C629D70FB0));
  }
  public ref CUtlVector<int> TransitionIndices {
    get => ref _Handle.AsRef<CUtlVector<int>>(Schema.GetOffset(0xD984C8C689E40507));
  }
  public ref CUtlVector<CStateActionUpdater> Actions {
    get => ref _Handle.AsRef<CUtlVector<CStateActionUpdater>>(Schema.GetOffset(0xD984C8C68D622684));
  }
  public AnimStateID StateID {
    get => new AnimStateIDImpl(_Handle + Schema.GetOffset(0xD984C8C65362B56B));
  }
  public SchemaUntypedField IsStartState {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0xD984C8C6B4CEE040));
  }
  public SchemaUntypedField IsEndState {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0xD984C8C65C2338AF));
  }
  public SchemaUntypedField IsPassthrough {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0xD984C8C6F0AD9431));
  }
  public SchemaUntypedField IsPassthroughRootMotion {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0xD984C8C64B319C83));
  }
  public SchemaUntypedField PreEvaluatePassthroughTransitionPath {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0xD984C8C60DFCB92D));
  }


}