// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CTakeDamageResultImpl : SchemaClass, CTakeDamageResult {

  public CTakeDamageResultImpl(nint handle) : base(handle) {
  }

  public CTakeDamageInfo OriginatingInfo {
    get => new CTakeDamageInfoImpl(_Handle + Schema.GetOffset(0xD4A7564D5B166E20));
  }
  public ref int HealthLost {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0xD4A7564D8F4D7431));
  }
  public ref int DamageTaken {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0xD4A7564DBADF2233));
  }
  public ref float PreModifiedDamage {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0xD4A7564D30D13E56));
  }
  public ref int TotalledHealthLost {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0xD4A7564DF5A9E972));
  }
  public ref int TotalledDamageDealt {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0xD4A7564D03ABE12B));
  }


}