// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CTargetSelectorUpdateNodeImpl : CAnimUpdateNodeBaseImpl, CTargetSelectorUpdateNode {

  public CTargetSelectorUpdateNodeImpl(nint handle) : base(handle) {
  }

  public ref TargetSelectorAngleMode_t AngleMode {
    get => ref _Handle.AsRef<TargetSelectorAngleMode_t>(Schema.GetOffset(0x37AB6CCBD21DC8BC));
  }
  public ref CUtlVector<CAnimUpdateNodeRef> Children {
    get => ref _Handle.AsRef<CUtlVector<CAnimUpdateNodeRef>>(Schema.GetOffset(0x37AB6CCB7415FA72));
  }
  public CAnimParamHandle TargetPosition {
    get => new CAnimParamHandleImpl(_Handle + Schema.GetOffset(0x37AB6CCBD1F40125));
  }
  public CAnimParamHandle TargetFacePositionParameter {
    get => new CAnimParamHandleImpl(_Handle + Schema.GetOffset(0x37AB6CCB1102D56F));
  }
  public CAnimParamHandle MoveHeadingParameter {
    get => new CAnimParamHandleImpl(_Handle + Schema.GetOffset(0x37AB6CCB3A7267CF));
  }
  public CAnimParamHandle DesiredMoveHeadingParameter {
    get => new CAnimParamHandleImpl(_Handle + Schema.GetOffset(0x37AB6CCBC6298DFB));
  }
  public ref bool TargetPositionIsWorldSpace {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0x37AB6CCBABCF9ECD));
  }
  public ref bool TargetFacePositionIsWorldSpace {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0x37AB6CCB504B4258));
  }
  public ref bool EnablePhaseMatching {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0x37AB6CCB6BC1372A));
  }
  public ref float PhaseMatchingMaxRootMotionSkip {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x37AB6CCB547A4008));
  }


}