// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CTonemapTriggerImpl : CBaseTriggerImpl, CTonemapTrigger {

  public CTonemapTriggerImpl(nint handle) : base(handle) {
  }

  public ref CUtlSymbolLarge TonemapControllerName {
    get => ref _Handle.AsRef<CUtlSymbolLarge>(Schema.GetOffset(0x82562698C641A282));
  }
  public ref CHandle<CEntityInstance> TonemapController {
    get => ref _Handle.AsRef<CHandle<CEntityInstance>>(Schema.GetOffset(0x82562698F5E1A34F));
  }


}