// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CTriggerDetectBulletFireImpl : CBaseTriggerImpl, CTriggerDetectBulletFire {

  public CTriggerDetectBulletFireImpl(nint handle) : base(handle) {
  }

  public ref bool PlayerFireOnly {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0x93930A3D56D51CFE));
  }
  public CEntityIOOutput OnDetectedBulletFire {
    get => new CEntityIOOutputImpl(_Handle + Schema.GetOffset(0x93930A3D11D6C936));
  }


}