// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CTwistConstraintImpl : CBaseConstraintImpl, CTwistConstraint {

  public CTwistConstraintImpl(nint handle) : base(handle) {
  }

  public ref bool Inverse {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0xA3EC320A0DE8C163));
  }
  public ref Quaternion ParentBindRotation {
    get => ref _Handle.AsRef<Quaternion>(Schema.GetOffset(0xA3EC320AE46C74E5));
  }
  public ref Quaternion ChildBindRotation {
    get => ref _Handle.AsRef<Quaternion>(Schema.GetOffset(0xA3EC320A0FCDDACB));
  }


}