// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CVoiceContainerDecayingSineWaveImpl : CVoiceContainerBaseImpl, CVoiceContainerDecayingSineWave {

  public CVoiceContainerDecayingSineWaveImpl(nint handle) : base(handle) {
  }

  public ref float Frequency {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x3383CD01D2C16DD7));
  }
  public ref float DecayTime {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x3383CD01E94A0656));
  }


}