// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CWeaponTaserImpl : CCSWeaponBaseGunImpl, CWeaponTaser {

  public CWeaponTaserImpl(nint handle) : base(handle) {
  }

  public GameTime_t FireTime {
    get => new GameTime_tImpl(_Handle + Schema.GetOffset(0xA91A6CB965DBC00C));
  }
  public ref int LastAttackTick {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0xA91A6CB90BCAAD3C));
  }

  public void FireTimeUpdated() {
    Schema.Update(_Handle, 0xA91A6CB965DBC00C);
  }
}