// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class EmptyTestScriptImpl : CAnimScriptBaseImpl, EmptyTestScript {

  public EmptyTestScriptImpl(nint handle) : base(handle) {
  }

  public SchemaUntypedField Test {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0xB7F6B6D5FAAC6DA3));
  }


}