// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class ExtraVertexStreamOverride_tImpl : BaseSceneObjectOverride_tImpl, ExtraVertexStreamOverride_t {

  public ExtraVertexStreamOverride_tImpl(nint handle) : base(handle) {
  }

  public ref uint SubSceneObject {
    get => ref _Handle.AsRef<uint>(Schema.GetOffset(0x38857FE855C3CCBC));
  }
  public ref uint DrawCallIndex {
    get => ref _Handle.AsRef<uint>(Schema.GetOffset(0x38857FE8FA5614D5));
  }
  public ref MeshDrawPrimitiveFlags_t AdditionalMeshDrawPrimitiveFlags {
    get => ref _Handle.AsRef<MeshDrawPrimitiveFlags_t>(Schema.GetOffset(0x38857FE8F0E57F2B));
  }
  public CRenderBufferBinding ExtraBufferBinding {
    get => new CRenderBufferBindingImpl(_Handle + Schema.GetOffset(0x38857FE800630FD0));
  }


}