// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class FeCtrlOsOffset_tImpl : SchemaClass, FeCtrlOsOffset_t {

  public FeCtrlOsOffset_tImpl(nint handle) : base(handle) {
  }

  public ref ushort CtrlParent {
    get => ref _Handle.AsRef<ushort>(Schema.GetOffset(0xA9B7D3DF55049230));
  }
  public ref ushort CtrlChild {
    get => ref _Handle.AsRef<ushort>(Schema.GetOffset(0xA9B7D3DF5BE48066));
  }


}