// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class HitReactFixedSettings_tImpl : SchemaClass, HitReactFixedSettings_t {

  public HitReactFixedSettings_tImpl(nint handle) : base(handle) {
  }

  public ref int WeightListIndex {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0x49C67E6F30288377));
  }
  public ref int EffectedBoneCount {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0x49C67E6F5D78F32A));
  }
  public ref float MaxImpactForce {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x49C67E6F30F6F9AC));
  }
  public ref float MinImpactForce {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x49C67E6F0A67F596));
  }
  public ref float WhipImpactScale {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x49C67E6FBE9EBA7B));
  }
  public ref float CounterRotationScale {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x49C67E6F8F00801B));
  }
  public ref float DistanceFadeScale {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x49C67E6FCE3774BC));
  }
  public ref float PropagationScale {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x49C67E6F5C590343));
  }
  public ref float WhipDelay {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x49C67E6F7E59F654));
  }
  public ref float SpringStrength {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x49C67E6F595D254F));
  }
  public ref float WhipSpringStrength {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x49C67E6F149D5369));
  }
  public ref float MaxAngleRadians {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x49C67E6F6654A2A4));
  }
  public ref int HipBoneIndex {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0x49C67E6F12FFBC70));
  }
  public ref float HipBoneTranslationScale {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x49C67E6F604F4D39));
  }
  public ref float HipDipSpringStrength {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x49C67E6F1C148301));
  }
  public ref float HipDipImpactScale {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x49C67E6F9856E173));
  }
  public ref float HipDipDelay {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x49C67E6F8A45177C));
  }


}