// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class InfoForResourceTypeCVSoundStackScriptListImpl : SchemaClass, InfoForResourceTypeCVSoundStackScriptList {

  public InfoForResourceTypeCVSoundStackScriptListImpl(nint handle) : base(handle) {
  }




}