// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class ModelBoneFlexDriver_tImpl : SchemaClass, ModelBoneFlexDriver_t {

  public ModelBoneFlexDriver_tImpl(nint handle) : base(handle) {
  }

  public ref CUtlString BoneName {
    get => ref _Handle.AsRef<CUtlString>(Schema.GetOffset(0xBCBDE5AAFDEE0E0C));
  }
  public ref uint BoneNameToken {
    get => ref _Handle.AsRef<uint>(Schema.GetOffset(0xBCBDE5AA44D1E369));
  }
  public ref CUtlVector Controls {
    get => ref _Handle.AsRef<CUtlVector>(Schema.GetOffset(0xBCBDE5AA5FCAD2B7));
  }


}