// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class PulseRuntimeDomainValueIndex_tImpl : SchemaClass, PulseRuntimeDomainValueIndex_t {

  public PulseRuntimeDomainValueIndex_tImpl(nint handle) : base(handle) {
  }

  public ref short Value {
    get => ref _Handle.AsRef<short>(Schema.GetOffset(0xCA672082DCB0894A));
  }


}