// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class RelationshipOverride_tImpl : Relationship_tImpl, RelationshipOverride_t {

  public RelationshipOverride_tImpl(nint handle) : base(handle) {
  }

  public ref CHandle<CBaseEntity> Entity {
    get => ref _Handle.AsRef<CHandle<CBaseEntity>>(Schema.GetOffset(0x2EECEBE0D33FF5DA));
  }
  public ref Class_T ClassType {
    get => ref _Handle.AsRef<Class_T>(Schema.GetOffset(0x2EECEBE040A47427));
  }


}