// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class ResponseContext_tImpl : SchemaClass, ResponseContext_t {

  public ResponseContext_tImpl(nint handle) : base(handle) {
  }

  public string Name {
    get {
      var ptr = _Handle.Read<nint>(Schema.GetOffset(0x8F5A90A274FF65FE));
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, 0x8F5A90A274FF65FE, value);
  } 
  public string Value {
    get {
      var ptr = _Handle.Read<nint>(Schema.GetOffset(0x8F5A90A28044B702));
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, 0x8F5A90A28044B702, value);
  } 
  public GameTime_t ExpirationTime {
    get => new GameTime_tImpl(_Handle + Schema.GetOffset(0x8F5A90A20389142D));
  }


}