// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class RsRasterizerStateDesc_tImpl : SchemaClass, RsRasterizerStateDesc_t {

  public RsRasterizerStateDesc_tImpl(nint handle) : base(handle) {
  }

  public ref RsFillMode_t FillMode {
    get => ref _Handle.AsRef<RsFillMode_t>(Schema.GetOffset(0x9C50E9DEFBCF0B4F));
  }
  public ref RsCullMode_t CullMode {
    get => ref _Handle.AsRef<RsCullMode_t>(Schema.GetOffset(0x9C50E9DE9B5ACDB6));
  }
  public ref bool DepthClipEnable {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0x9C50E9DED003B21B));
  }
  public ref bool MultisampleEnable {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0x9C50E9DEA3D615E7));
  }
  public ref int DepthBias {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0x9C50E9DE7042005B));
  }
  public ref float DepthBiasClamp {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x9C50E9DEA541A904));
  }
  public ref float SlopeScaledDepthBias {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x9C50E9DE4E34B6FC));
  }


}