// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class VMixShaperDesc_tImpl : SchemaClass, VMixShaperDesc_t {

  public VMixShaperDesc_tImpl(nint handle) : base(handle) {
  }

  public ref int Shape {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0x80E2A73621208A02));
  }
  public ref float FldbDrive {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x80E2A7360E12679B));
  }
  public ref float FldbOutputGain {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x80E2A73667F97C23));
  }
  public ref float WetMix {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x80E2A736D5453C15));
  }
  public ref int OversampleFactor {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0x80E2A736142D0AF2));
  }


}