// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class VsInputSignature_tImpl : SchemaClass, VsInputSignature_t {

  public VsInputSignature_tImpl(nint handle) : base(handle) {
  }

  public ref CUtlVector<VsInputSignatureElement_t> Elems {
    get => ref _Handle.AsRef<CUtlVector<VsInputSignatureElement_t>>(Schema.GetOffset(0xA7BF24E33F2FC92B));
  }
  public ref CUtlVector<VsInputSignatureElement_t> Depth_elems {
    get => ref _Handle.AsRef<CUtlVector<VsInputSignatureElement_t>>(Schema.GetOffset(0xA7BF24E3C1AC112D));
  }


}