// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class WeightListImpl : SchemaClass, WeightList {

  public WeightListImpl(nint handle) : base(handle) {
  }

  public ref CUtlString Name {
    get => ref _Handle.AsRef<CUtlString>(Schema.GetOffset(0x4A08DD454D8F5786));
  }
  public ref CUtlVector<float> Weights {
    get => ref _Handle.AsRef<CUtlVector<float>>(Schema.GetOffset(0x4A08DD4577B2F91E));
  }


}