// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_INIT_RemapNamedModelMeshGroupToScalarImpl : C_INIT_RemapNamedModelElementToScalarImpl, C_INIT_RemapNamedModelMeshGroupToScalar {

  public C_INIT_RemapNamedModelMeshGroupToScalarImpl(nint handle) : base(handle) {
  }




}