// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_INIT_StatusEffectCitadelImpl : CParticleFunctionInitializerImpl, C_INIT_StatusEffectCitadel {

  public C_INIT_StatusEffectCitadelImpl(nint handle) : base(handle) {
  }

  public ref float SFXColorWarpAmount {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x6420071B7AE5DF43));
  }
  public ref float SFXNormalAmount {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x6420071BACB8EED5));
  }
  public ref float SFXMetalnessAmount {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x6420071B02A1BB5A));
  }
  public ref float SFXRoughnessAmount {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x6420071BC6E86EA4));
  }
  public ref float SFXSelfIllumAmount {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x6420071B7BD60AE5));
  }
  public ref float SFXSScale {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x6420071BCA52F1F3));
  }
  public ref float SFXSScrollX {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x6420071BF8557E0E));
  }
  public ref float SFXSScrollY {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x6420071BF9557FA1));
  }
  public ref float SFXSScrollZ {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x6420071BF6557AE8));
  }
  public ref float SFXSOffsetX {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x6420071BFA92D3C0));
  }
  public ref float SFXSOffsetY {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x6420071BFB92D553));
  }
  public ref float SFXSOffsetZ {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x6420071BFC92D6E6));
  }
  public ref DetailCombo_t DetailCombo {
    get => ref _Handle.AsRef<DetailCombo_t>(Schema.GetOffset(0x6420071B928C6606));
  }
  public ref float SFXSDetailAmount {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x6420071B5B8C7946));
  }
  public ref float SFXSDetailScale {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x6420071BCC4A4840));
  }
  public ref float SFXSDetailScrollX {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x6420071BF45EED31));
  }
  public ref float SFXSDetailScrollY {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x6420071BF35EEB9E));
  }
  public ref float SFXSDetailScrollZ {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x6420071BF25EEA0B));
  }
  public ref float SFXSUseModelUVs {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x6420071B8F106179));
  }


}