// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_SetControlPointToVectorExpressionImpl : CParticleFunctionPreEmissionImpl, C_OP_SetControlPointToVectorExpression {

  public C_OP_SetControlPointToVectorExpressionImpl(nint handle) : base(handle) {
  }

  public ref VectorExpressionType_t Expression {
    get => ref _Handle.AsRef<VectorExpressionType_t>(Schema.GetOffset(0x67E9EFDE160B2427));
  }
  public ref int OutputCP {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0x67E9EFDE50DF5703));
  }
  public CParticleCollectionVecInput Input1 {
    get => new CParticleCollectionVecInputImpl(_Handle + Schema.GetOffset(0x67E9EFDEE17F27DA));
  }
  public CParticleCollectionVecInput Input2 {
    get => new CParticleCollectionVecInputImpl(_Handle + Schema.GetOffset(0x67E9EFDEE07F2647));
  }
  public CPerParticleFloatInput Lerp {
    get => new CPerParticleFloatInputImpl(_Handle + Schema.GetOffset(0x67E9EFDE622FAB06));
  }
  public ref bool NormalizedOutput {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0x67E9EFDE0AA98C55));
  }


}