// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CCompressorGroupImpl : SchemaClass, CCompressorGroup {

  public CCompressorGroupImpl(nint handle) : base(handle) {
  }

  public ref int TotalElementCount {
    get => ref _Handle.AsRef<int>(Schema.GetOffset(0x8D9A46F69E4F56A2));
  }
  public ref CUtlVector<CString> ChannelClass {
    get => ref _Handle.AsRef<CUtlVector<CString>>(Schema.GetOffset(0x8D9A46F68F5E9AD5));
  }
  public ref CUtlVector<CString> VariableName {
    get => ref _Handle.AsRef<CUtlVector<CString>>(Schema.GetOffset(0x8D9A46F6369599AB));
  }
  public ref CUtlVector<fieldtype_t> Type {
    get => ref _Handle.AsRef<CUtlVector<fieldtype_t>>(Schema.GetOffset(0x8D9A46F618853D59));
  }
  public ref CUtlVector<int> Flags {
    get => ref _Handle.AsRef<CUtlVector<int>>(Schema.GetOffset(0x8D9A46F6CE6E9C28));
  }
  public ref CUtlVector<CUtlString> Grouping {
    get => ref _Handle.AsRef<CUtlVector<CUtlString>>(Schema.GetOffset(0x8D9A46F64308F10D));
  }
  public ref CUtlVector<int> CompressorIndex {
    get => ref _Handle.AsRef<CUtlVector<int>>(Schema.GetOffset(0x8D9A46F67B4BF604));
  }
  public ref CUtlVector<CUtlVector<CString>> ElementNames {
    get => ref _Handle.AsRef<CUtlVector<CUtlVector<CString>>>(Schema.GetOffset(0x8D9A46F6D5BFAA00));
  }
  public ref CUtlVector<CUtlVector<int>> ElementUniqueID {
    get => ref _Handle.AsRef<CUtlVector<CUtlVector<int>>>(Schema.GetOffset(0x8D9A46F64C95C12D));
  }
  public ref CUtlVector<uint> ElementMask {
    get => ref _Handle.AsRef<CUtlVector<uint>>(Schema.GetOffset(0x8D9A46F67BBE1B07));
  }
  public ref CUtlVector<PointerTo<SchemaUntypedField>> VectorCompressor {
    get => ref _Handle.AsRef<CUtlVector<PointerTo<SchemaUntypedField>>>(Schema.GetOffset(0x8D9A46F61A8B6EBF));
  }
  public ref CUtlVector<PointerTo<SchemaUntypedField>> QuaternionCompressor {
    get => ref _Handle.AsRef<CUtlVector<PointerTo<SchemaUntypedField>>>(Schema.GetOffset(0x8D9A46F6D4D751D4));
  }
  public ref CUtlVector<PointerTo<SchemaUntypedField>> IntCompressor {
    get => ref _Handle.AsRef<CUtlVector<PointerTo<SchemaUntypedField>>>(Schema.GetOffset(0x8D9A46F654D409FB));
  }
  public ref CUtlVector<PointerTo<SchemaUntypedField>> BoolCompressor {
    get => ref _Handle.AsRef<CUtlVector<PointerTo<SchemaUntypedField>>>(Schema.GetOffset(0x8D9A46F6359E7C24));
  }
  public ref CUtlVector<PointerTo<SchemaUntypedField>> ColorCompressor {
    get => ref _Handle.AsRef<CUtlVector<PointerTo<SchemaUntypedField>>>(Schema.GetOffset(0x8D9A46F6088C2B29));
  }
  public ref CUtlVector<PointerTo<SchemaUntypedField>> Vector2DCompressor {
    get => ref _Handle.AsRef<CUtlVector<PointerTo<SchemaUntypedField>>>(Schema.GetOffset(0x8D9A46F633C3F00D));
  }
  public ref CUtlVector<PointerTo<SchemaUntypedField>> Vector4DCompressor {
    get => ref _Handle.AsRef<CUtlVector<PointerTo<SchemaUntypedField>>>(Schema.GetOffset(0x8D9A46F6E178618F));
  }


}