// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmBoneMaskSelectorNode__CDefinitionImpl : CNmBoneMaskValueNode__CDefinitionImpl, CNmBoneMaskSelectorNode__CDefinition {

  public CNmBoneMaskSelectorNode__CDefinitionImpl(nint handle) : base(handle) {
  }

  public ref short DefaultMaskNodeIdx {
    get => ref _Handle.AsRef<short>(Schema.GetOffset(0xA90158701E92549D));
  }
  public ref short ParameterValueNodeIdx {
    get => ref _Handle.AsRef<short>(Schema.GetOffset(0xA90158702696FA7C));
  }
  public ref bool SwitchDynamically {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0xA9015870461869F8));
  }
  public SchemaUntypedField MaskNodeIndices {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0xA90158703326692E));
  }
  public SchemaUntypedField ParameterValues {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0xA90158709D777E36));
  }
  public ref float BlendTimeSeconds {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0xA90158706D3A08FC));
  }


}