// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPointClientUIDialogImpl : CBaseClientUIEntityImpl, CPointClientUIDialog {

  public CPointClientUIDialogImpl(nint handle) : base(handle) {
  }

  public ref CHandle<CBaseEntity> Activator {
    get => ref _Handle.AsRef<CHandle<CBaseEntity>>(Schema.GetOffset(0x1136C185AB093BB2));
  }
  public ref bool StartEnabled {
    get => ref _Handle.AsRef<bool>(Schema.GetOffset(0x1136C185500D5C24));
  }

  public void ActivatorUpdated() {
    Schema.Update(_Handle, 0x1136C185AB093BB2);
  }
}