// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CRevertSavedImpl : CModelPointEntityImpl, CRevertSaved {

  public CRevertSavedImpl(nint handle) : base(handle) {
  }

  public ref float LoadTime {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x8E0EAC0F9925A540));
  }
  public ref float Duration {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x8E0EAC0F9879A98D));
  }
  public ref float HoldTime {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x8E0EAC0F105A1BF1));
  }


}