// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CStopAtGoalUpdateNodeImpl : CUnaryUpdateNodeImpl, CStopAtGoalUpdateNode {

  public CStopAtGoalUpdateNodeImpl(nint handle) : base(handle) {
  }

  public ref float OuterRadius {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x4889F8297B66A818));
  }
  public ref float InnerRadius {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x4889F82932121407));
  }
  public ref float MaxScale {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x4889F829FF4EC8E7));
  }
  public ref float MinScale {
    get => ref _Handle.AsRef<float>(Schema.GetOffset(0x4889F829D125D67D));
  }
  public CAnimInputDamping Damping {
    get => new CAnimInputDampingImpl(_Handle + Schema.GetOffset(0x4889F82915440FB5));
  }


}