// <auto-generated />

using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class PulseGraphExecutionHistoryNodeDesc_tImpl : SchemaClass, PulseGraphExecutionHistoryNodeDesc_t {

  public PulseGraphExecutionHistoryNodeDesc_tImpl(nint handle) : base(handle) {
  }

  public ref CBufferString StrCellDesc {
    get => ref _Handle.AsRef<CBufferString>(Schema.GetOffset(0x7F4ECA02AD3F01DD));
  }
  public SchemaUntypedField StrBindingName {
    get => new SchemaUntypedField(_Handle + Schema.GetOffset(0x7F4ECA021A5069AA));
  }


}